### ISSUE TITLE
Introduce a data access layer in API

### ISSUE THREAD

**Issue by csleead** [Covid-19Radar/Covid19Radar#110]
The APIs have hard dependencies on Cosmos DB API, which makes unit testing very difficult.
Perhaps we should do some refactoring and introduce a data access layer.

**Comment by csleead** [comment]
@darkcrash any problems?

**Comment by darkcrash** [comment]
@csleead 
hello !
I think that it is difficult to automate the test of the data access itself even if the data layer layer is put.

I think automated unit testing can do this.
- Taking advantage of Mock to take coverage
- What to expect with data-driven testing
Per method

I think we need to consider e2E testing to check operations.

**Comment by csleead** [comment]
@darkcrash 
Testing the data access is usually difficult.
However, the data access should not contains any thing complex in the first place, they can be as simple as an one-liner calling **Container.CreateItemAsync()** for example, which means **NOT unit testing them** should not be a very big deal.

The problem we are now facing is that data access logic are not encapsulated, which makes unit testing **OTHER** code, like the service classes, very difficult. That's why I suggest introducing some data access interfaces and classes so that we can easily mock the data access when unit testing.

For the e2e testing, I think we should put it aside until we have proper unit testing in place.

**Comment by darkcrash** [comment]
@csleead 
I see.
There are certainly some things that depend on the inside of the service.
"Container.CreateItemAsync()" is it possible to avoid it with the container Mock?

**Comment by darkcrash** [comment]
@csleead 
Like this?
```CSharp
interface IUserDataAccess {
    UserDataModel Get(IUser user);
}
class UserDataAccess : IUserDataAccess {
     public UserDataModel Get(IUser user) {
         var q await Cosmos.User.ReadItemAsync<UserResultModel>(user.GetId(), PartitionKey.None);
        ....
         return result;
     }
}
```

**Comment by csleead** [comment]
@darkcrash 
Exactly

**Comment by darkcrash** [comment]
@csleead 
I think it's a good idea. Some classes have the same data access.
