### ISSUE TITLE
Enable C# 8.0 nullable in API projects

### ISSUE THREAD

**Issue by csleead** [Covid-19Radar/Covid19Radar#112]
It helps to avoid NullReferenceException and make the code cleaner.

**Comment by darkcrash** [comment]
@csleead 
thank you for your Issue!
I think it's a good idea.

However, there is a great advantage in being able to write the same way as xamarin.
I think it's important to be the same as Xamarin when introducing "C# 8.0 nullable" into the API.
At this point, we are aiming for an early release, and it may be difficult to implement it.

**Comment by csleead** [comment]
@darkcrash 
Actually, I just tried to see how difficult it is to enable nullable in project level and fix all the warning.
It turns out it is indeed quite difficult. I think the best way to introduce nullable is to have
nullable enabled in new code files and to enable nullable in old files when we make changes on them.

**Comment by darkcrash** [comment]
@csleead

**Comment by csleead** [comment]
@darkcrash 
We don't have to correct in one go. We can enable nullable only when we found it is not difficult. Little improvement is better than no improvement.

**Comment by darkcrash** [comment]
@csleead 
Considering the impact on Xamarin, i think it's a good idea to step up from the Tests project.
This is because the Model of the Api project is often shared with Xamarin, making it difficult to be strict in CosmosDB without type definitions. False rigor leads to new glitches. It takes time.
We believe that the check process that focuses on the elements required by the method is more realistic in the current update.

**Comment by csleead** [comment]
@darkcrash 
Models are actually the most troublesome part when introducing nullable, we don't have to touch the models for now if we don't have enough confidence.

By the way, sharing models between client and server is usually a bad practice, it is something we should get rid of.

**Comment by darkcrash** [comment]
@csleead 
Let's see. There is no strict share, but any property that has the same meaning must match the type and name.
We think it is preferable that they are the same description.
thanks.
