### ISSUE TITLE
Should not use TOTP to generate OTP

### ISSUE THREAD

**Issue by csleead** [Covid-19Radar/Covid19Radar#120]
In the OtpSendApi, we expect it to generate a OTP which is valid for 30 seconds.
However, we are now using TOTP which means there is no guarantee on how long the OTP we sent to user is valid.

One alternative is to replace TOTP will simple random number OTP and have the OTP stored in data base for later comparison.

**Comment by changeworld** [comment]
Thank you for your feedback.

The following two methods are defined for OTP generation.

- [HOTP](https://tools.ietf.org/html/rfc4226)
- [TOTP](https://tools.ietf.org/html/rfc6238)

None of your alternatives exist, and I think we should avoid adopting this app this time.

**Comment by csleead** [comment]
@changeworld 
HOTP and TOTP are just two OTP generation methods defined in RFC, but **THE TWO** methods everyone **MUST** use.

For our use case, which is just for registration, it seems TOTP is absolutely not suitable, HOTP might work but I don't see any difference between using simple random number OTP and HOTP.

I am not an expert about security, correct me if I were wrong.
