### ISSUE TITLE
docs/Update Documents for Android Testers.

### ISSUE THREAD

**Issue by kmikage** [Covid-19Radar/Covid19Radar#123]
- for iOS Version(ja)
- for Android Version(ja)

現状に即したものに変更

**Comment by kmikage** [comment]
#125 
Android向けドキュメントをpull request.

**Comment by kmikage** [comment]
#128 
update for android testers.
- add how-to-update apps.
- fix more.

**Comment by kmikage** [comment]
iOS版については、#129 にIssueを分割。

**Comment by changeworld** [comment]
refs: #128
