### ISSUE TITLE
docs/Update Documents for iOSTesters.

### ISSUE THREAD

**Issue by kmikage** [Covid-19Radar/Covid19Radar#129]
- for iOS Version(ja)
#128 と同様の内容にアップデート。

**Comment by kmikage** [comment]
Pull requested.
Android版(#128 )と同様の内容です。
#130

**Comment by changeworld** [comment]
https://github.com/Covid-19Radar/Covid19Radar/pull/130#issuecomment-623374409

上記指摘のため、一旦クローズします。
