### ISSUE TITLE
The application doesn't start

### ISSUE THREAD

**Issue by yoichinak** [Covid-19Radar/Covid19Radar#139]
1. Install the App.
1. Completes the tutorial and HOME page is appears.
1. The app does **not** ask permissions of location and Bluetooth.
1. Tap "Detected Beacon List" button.
1. App asks permission of Bluetooth.
1. At the same time the app shuts down.
1. Then the app doesn't start.

Build : 222-228
Platform : iOS
OS Version : 13.3.1
Device : iPhone 11

1. アプリをインストールする。
1. チュートリアルを終了すると「ホーム」ページが表示される。
1. このとき位置情報とBluetoothのアクセス許可を求められない。（仕様かもしれませんが）
1. 「検出ビーコン一覧」ボタンをタップする。
1. Bluetooth のアクセス許可を求められる。
1. 同時にアプリが落ちる。
1. それ以降、アプリは起動できない。

Build 222-228 で発生します。
Build 221 はチュートリアルを終了できません。
Build 218-220 は存在しないようです。
Build 217 までは大丈夫でした。

**Comment by noriji** [comment]
テスターにご参加いただきありがとうございます。

先程、一斉メール送信させていただいた内容と重複する部分がありますが、この数日間、テスター参加いただいている「Covid19Radar」アプリが急に停止する、画面続行ができない、起動できない等の状況になっております。
これは現在、コードに大幅な変更を加えていることに起因するものです。
実装に関しては次期OSバージョンを使う必要がある部分も含まれておりますため、現時点では限られた環境のみで動作する形となっております。

上記ご報告いただいた内容を解消するには多少のお時間を頂く形となりますため、一旦テストを中止いただけますと幸いです。
テスト再開時には改めて一斉メール送信にてご連絡差し上げる予定です。
ご理解のほど、よろしくお願いいたします。
