### ISSUE TITLE
Not display Japanese in "Allow Exposure Notification / Bluetooth" page

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#152]
"Allow Exposure Notification / Bluetooth" ページが英語で表示される
at Covid19RadarAndroid 1.0 (246)
on Nexus 7, Android 6.0.1

**Comment by oyasan-ba2** [comment]
Comment from デプロイ王子 Kazumi Hirose @ COVID19Radar: @kazumihirose
>いえ、これ英語UIのテスト中でして、日本語はできてます

**Comment by kazumihirose** [comment]
ありがとうございます。こちらの要領で日本語訳の追加をお願いできますと幸いです。
https://github.com/Covid-19Radar/Covid19Radar/blob/master/HOW_TO_TRANSRATE_CONTRIBUTE.md

**Comment by oyasan-ba2** [comment]
翻訳確認した結果が反映されないと悩んでいたのですが、やっと理由がわかりました。
Covid19Radar/MultilingualResources/*.xlf のoriginalのパスが誤っていたため、多言語アプリツールキットの有効化がうまく動かないためでした。

file datatype="xml" source-language="en-US" target-language="ja" original="COVID19RADAR/RESX/APPRESOURCES.RESX" tool-id="MultilingualAppToolkit" product-name="n/a" product-version="n/a" build-num="n/a"

を
"COVID19RADAR/RESOURCES/APPRESOURCES.RESX"
に変更すると、うまく自動翻訳、翻訳言語の追加が出来るようになります。

**Comment by oyasan-ba2** [comment]
Covid19Radar.es の state に閉じていない""がありました

**Comment by oyasan-ba2** [comment]
P3-プライバシーポリシー で追加していただいた ButtonNotAgree の文字列定義がないです

**Comment by oyasan-ba2** [comment]
他に、
DescriptionPageTextStep1Description2
DescriptionPageTextStep2Description2
が未定義文字列でしたので、日本語 -> 英語翻訳を英語部分に設定して自動翻訳し、review必要フラグを立てておきます

**Comment by oyasan-ba2** [comment]
気づいた点を修正して、build確認、Tutorialページ確認の上、pull request しました。
Reviewよろしくお願いいたします。

**Comment by changeworld** [comment]
refs #256

**Comment by oyasan-ba2** [comment]
P3-プライバシーポリシー で追加していただいた ButtonNotAgree の文字列定義がないです in AppResources.resx

**Comment by oyasan-ba2** [comment]
DescriptionPageTextStep1Description2 の値がSampleTextのままです  in AppResources.resx
DescriptionPageTextStep2Description2 の値がSampleTextのままです in AppResources.resx
これでは多言語Resource fileに正しい英語文字列が反映されないため、翻訳、翻訳確認できません

**Comment by oyasan-ba2** [comment]
上記コメントが理解できなければ、私のpull requestを確認してくださいませ！
