### ISSUE TITLE
Not display version number

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#153]
UI上にバージョン番号、Build番号を表示する場所がない
at Covid19RadarAndroid 1.0 (246)
on Nexus 7, Android 6.0.1

**Comment by oyasan-ba2** [comment]
プロトタイプ画面（日本語）も確認したが無し。アプリのユーザーサポート時に必要になると考えられる。
https://xd.adobe.com/view/9ccfd774-5667-4373-530f-591148c84aab-eafe/

**Comment by oyasan-ba2** [comment]
バージョン番号は、通常ユーザーには必要なし、問題に遭遇したユーザーに必須の情報なので、Homeではなく、「このアプリについて」(About)などのサブメニュー内に隠した方がユーザーの混乱を避けれると思います。
例: スマートフォンアプリ - 電子お薬手帳(電子おくすり手帳) harmo(ハルモ)
https://www.harmo.biz/customer/app/

**Comment by changeworld** [comment]
最新のデザインですと、ハンバーガーメニュー=>アプリの設定で遷移する画面にVersionを表示する項目が存在していましたのでクローズします。
