### ISSUE TITLE
Android 5.1.1 Connection Error

### ISSUE THREAD

**Issue by takker0708** [Covid-19Radar/Covid19Radar#166]
Hi.

A connection error occurred during the registration process after agreeing to the Android app's privacy policy.
Do I need a SIM card?

Version: Android 5.1.1
Wifi: ON
Mobile Data: No SIM
Buletooth: ON

Sincerely.

**Comment by oyasan-ba2** [comment]
Thank you for your report!. I confirmed your same issue of Covid19RadarAndroid 1.0(264) on Xperia Compact, Android 7.0, Wifi connected, No SIM.
I will confirm that this issue occurs with SIM or not.

**Comment by oyasan-ba2** [comment]
@takker0708 I confirmed to disappear this issue at the latest version: 1.0(275). Could you try to re-install the latest version and reproduce this ?

**Comment by takker0708** [comment]
@oyasan-ba2 
I've also confirmed that this Issue has been resolved in the latest version:1.0(277).

Close this issue. Thank you!
