### ISSUE TITLE
Bugfix/iOS版でアクセス許可が表示される場面

### ISSUE THREAD

**Issue by kmikage** [Covid-19Radar/Covid19Radar#17]
iOS版にて、アクセス許可のタイミングが異なる。
・Bluetooth, GPS - 初回起動時、Home表示時
・通知 - 初回もしくは次回起動時、Home表示時

想定される動作）
・通知, Bluetooth, GPSが、「デバイスへのアクセス許可」画面のタイミングで同時にアクセス許可を行う。
https://github.com/kmikage/Covid19Radar-1/blob/Future/7/doc/How-to-use/.attachments/iPhone-Bluetooth-Information-SS.png

発生環境）
・iPhone 7 / iOS Version 13.3.1
・COVID-19 Radar iOS Version 1.0 (184)

**Comment by changeworld** [comment]
最新のUI/UXでは変更されているので一旦クローズします。
