### ISSUE TITLE
Start button is difficult to understand by color barrier persons

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#178]
スタートボタンの背景と文字の明度差が少ないので、カラーバリアを持つ人が開始ボタンとわかりにくい

Covid19RadarAndroid 1.0(263) on Nexus7, Android 6.0.1

**Comment by oyasan-ba2** [comment]
カラーユニバーサルデザイン　の明度差の部分を考慮してもらえますでしょうか
https://ja.wikipedia.org/wiki/%E3%82%AB%E3%83%A9%E3%83%BC%E3%83%A6%E3%83%8B%E3%83%90%E3%83%BC%E3%82%B5%E3%83%AB%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3

**Comment by changeworld** [comment]
ご意見ありがとうございました。
UI/UXの改善のご意見のため、UI/UX含めたデザインを見ていただいている @noriji さんに連携します。

**Comment by noriji** [comment]
ご意見ありがとうございます。
このご意見をいただいた時点では開発中の画面が出ていたのではないかと思いますが、UI/UXの改善に関してはアドバイザーの方の意見も参考に随時対応していっております。

UI/UXデザイン（文言含む）は随時変更を行っており頻繁に内容が変わってしまっているため、現時点では一旦テストを止めております。
テスト再開時にはテスターの皆様にメールにて改めてお知らせいたしますので、その際にはよろしくお願いいたします。
