### ISSUE TITLE
Use the same terminology for this application

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#179]
このアプリ"COVID19Radar"の表記が、UIに表示される場所によってバラバラなので、統一してください。

アプリケーション名: Covid19Radar
起動時のスプラッシュ画面: COVID-19Radar
Home: COVID19Radar

Application Identity, Branding 的にも、統一した方が有利と思います。

**Comment by changeworld** [comment]
@oyasan-ba2 
ご指摘ありがとうございました。

**Comment by oyasan-ba2** [comment]
Covid19Radar に統一するということですね。了解です。
@changeworld 早速の対応ありがとうございます。
下記の修正もお願いできますでしょうか
>P0-splash screen(起動時のスプラッシュ画面): COVID-19Radar

**Comment by changeworld** [comment]
@oyasan-ba2 

> Covid19Radar に統一するということですね。了解です。

まだどこに統一するのか決まっていません。

COVID19RadarとCovid19Radarは揺れなので一旦統一する修正をしています。

何に統一するのか決まり次第、それにすべて統一する予定です。

**Comment by oyasan-ba2** [comment]
@changeworld 暫定修正、了解です。

**Comment by changeworld** [comment]
@oyasan-ba2 
「COVID-19Radar」に統一させていただきました。
