### ISSUE TITLE
CHS Translation

### ISSUE THREAD

**Issue by foxdave** [Covid-19Radar/Covid19Radar#189]
I don't use git often so I am not sure I was doing right. So attach the resource file here too.
I added missing keys compared to AppResources.resx and correct some not proper translations.
[AppResources.zh-Hans.zip](https://github.com/Covid-19Radar/Covid19Radar/files/4637799/AppResources.zh-Hans.zip)

**Comment by kazumihirose** [comment]
Thank you!!! I've listed contributers list!
