### ISSUE TITLE
This application can start on BLE unsupported device

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#192]
Covid19RadarAndroid をBLE非サポート機器上でインストール、スタートできてしまう。

インストール時、もしくは、Bluetooh開始Dialog(P4-デバイス設定)でチェックして、それ以上先に進まないようにする必要がある。

Checked on Nexus 7, Android 6.0.1, Bluetooth V3.0+EDR (w/o BLE)

**Comment by oyasan-ba2** [comment]
Need follows:
<uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
https://developer.android.com/guide/topics/connectivity/bluetooth-le?hl=ja#permissions

**Comment by kazumihirose** [comment]
現在、BLEをベタに使う仕組みからGoogle / Appleとの共同開発を行っているENに変更を進めています。いったん保留とさせてください。

**Comment by oyasan-ba2** [comment]
@kazumihirose このPJは、もっとも重要なENが最後に仕様決定し、最後に提供・統合される流れになってしまっているので、逆に他に部分は先に詰めておかなければ、タイムリーなリリースが出来ないと考えています。
このため、先に2次系(異常系ではない、主ケースではないがありえるケース)を想定し、UI/UX設計し、デザインしておく必要があると思います。また、ユーザー層が広いのでデザインは十分考慮する必要あり=時間がかかると思っています。
EN(Exposure Notification = Contact Tracing API 0.4)のStatusにはHW仕様がらみのコードは定義されていないため、HW仕様がらみは、ENの外側で解決する必要があるという認識でいます。
先に、この辺を始めて頂けないか、ぜひ検討してみてください。

**Comment by darkcrash** [comment]
要約すると、基本はOSおよびAPIを提供するAndroid iOS に任せることになりますが、
その場合に上手く動作しないときのUI/UXがあるといいのではないかってことですかね。

HW仕様に関しては、ENの実装有無をAndroidと各デバイスベンダーで解決してくれることを願います。
ただ使う側の視点として見るならば動く動かないは知りたいと。
アプリケーションとしては、動作確認機器のリストを作るあたりが落としどころになるんじゃないかと思います。そのあたりはテスターの方々の力を借りているところですね。

BLEの仕様も気づけばアップデートされてるようですね。

https://blog.google/documents/70/Exposure_Notification_-_Bluetooth_Specification_v1.2.2.pdf

**Comment by oyasan-ba2** [comment]
ユーザーは、動作確認機器のリストなんかは見ないで、とりあえずインストールして使おうとすると思いますけど、EN APIも実装中で変わる可能性があるのは待つことは了解です。

>HW仕様に関しては、ENの実装有無をAndroidと各デバイスベンダーで解決してくれることを願います。
Android OSに組み込まれれば、デバイスベンダーの責務になりますが、開発者サービスとして提供される間はアプリの責務になるという理解です。

**Comment by darkcrash** [comment]
> Android OSに組み込まれれば、デバイスベンダーの責務になりますが、開発者サービスとして提供される間はアプリの責務になるという理解です。(アプリもGoogleは提供しないと言っているので、Google商用アプリのようにそれをプリインして提供するデバイスベンダーの責務にはなりません)

少し深いところでいえば、BL、BLEのハードウェア含めた実装がどうなっているかは、デバイスに依存しています。
アプリとしては、それが動くか動かないか以外にできるアクションが何かあれば良いですが、ENのAPIは直接のBLE操作を許してしまうことを避けているように思えます。
少し前にとあるデバイスでBLEのHW実装がないところでこのアプリを動かしたところ、不正なBLEパケットが送信されてしまうことはありました。
これらに対しては、BLEのPAYLOADを送出することは難しく、
アプリとして扱えないとする以外の選択肢はないという認識です。

何かこれらに具体的な解決策をお持ちでしょうか？

**Comment by oyasan-ba2** [comment]
>アプリとしては、それが動くか動かないか以外にできるアクションが何かあれば良いですが、ENの>APIは直接のBLE操作を許してしまうことを避けているように思えます。
EN APIのスコープ外ということです。EN APIが動作する環境であることは、アプリが保証してやる必要があると考えます。
HW: Bluetooth 4.0 or upper
https://ja.wikipedia.org/wiki/Bluetooth#%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3

Android: API的に出来るのは下記
in AndroidManifest.xml
uses-permission android:name="android.permission.BLUETOOTH_ADMIN"
uses-permission android:name="android.permission.BLUETOOTH"
uses-feature android:name="android.hardware.bluetooth_le" android:required="true"
これで、BLE非対応デバイスでは、Google Playからインストールできなくなります。
(iOSは詳しくないのでご勘弁を！)

ただ、最後は、ユーザーが、「Bluetoothが使える(ON/OFFが付いている)のに、なんで使えないの？？？」とコールが山ほど入りそうなので、悩ましいところです。
アプリはインストール可について、丁寧な説明を出す方がユーザーにとっても、ユーザーサポートにとっても、良いかもしれません。

**Comment by darkcrash** [comment]
検討ありがとうございます。
デザインUI/UXは、 @noriji さんに連携しました。

もしよければ、PR出してみてください。
クライアントアプリは @kazumihirose さんが中心なので、私が判断しかねるところではありますが、取り込んでくれるかもしれません。
その時は、ぜひ貢献者リストに記名した変更もPRに含めてくださいますようお願いします

**Comment by oyasan-ba2** [comment]
EN API仕様の方も更新されてました。
https://static.googleusercontent.com/media/www.google.com/ja//covid19/exposurenotifications/pdfs/Android-Exposure-Notification-API-documentation-v1.3.1.pdf

**Comment by oyasan-ba2** [comment]
Android-Exposure-Notification-API-documentation-v1.3.1.pdf によると、
FAILED_BLUETOOTH_SCANNING_DISABLED が、
(1) Bluetooth Disableのとき
は返ってきそうですが、
(2) BLE Unsupportedのとき
は、FAILED_BLUETOOTH_SCANNING_DISABLED よりはFAILED_INTERNALが返ってくるように見えてます。

また、Android 6.0 (API 23) からサポートに変わっています(ref. "Google Play services" in above document)

**Comment by oyasan-ba2** [comment]
pull requestしておきました。
なお、これを取り込むと、対応バージョンが Android 6.0 or later になります。
App Center の Covid19RadarAndroid で表示されるバージョンも、あわせて変更をお願いしてもよいでしょうか。(App Centerの変更方法がわかっていないので)
