### ISSUE TITLE
Need Disagree button in P3-PrivacyPolicy

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#198]
P3-プライバシーポリシー に"同意しない"ボタンと、その後のフローがない。
個人情報保護法の観点から、同意の撤回が出来る必要がある認識です。
個人情報保護法 "同意の撤回"
https://www.senshu-u.ac.jp/School/horitu/researchcluster/hishiki/hishiki_db/thj0090/personaldataact.html
(何度か改正が入っているようなので、現在は変わっているかもしれません)

**Comment by changeworld** [comment]
@oyasan-ba2 
ご指摘ありがとうございます。

### "同意しない"ボタンと、その後のフローがない。
フローに関しては要望を受けて随時更新しているため、本日時点では「同意しない」ボタンが追加されております。
また、同意しない場合はアプリは使えないため、「その後のフローがない。」については問題ないかと思います。

### 個人情報保護法の観点から、同意の撤回が出来る必要がある認識です。

本アプリは「個人情報保護法」が定義する個人情報は取得しておりません。

> 個人情報（こじんじょうほう）とは、任意の一人の個人に関する情報であり、かつその情報に含まれる記述等によって特定の個人を識別できるものを指す。

収集している情報はアプリ利用者が別のアプリ利用者との接触記録のため、その情報から「特定の個人」を識別することはできません。

**Comment by oyasan-ba2** [comment]
close後ですが、記録に残すために記載しておきます。
>本日時点では「同意しない」ボタンが追加されております。
最新でUI/UX修正されていることを確認済みです。

>個人情報は取得しておりません
以前のUI/UXフロー? で電話番号を入力するフローになっていたため、現状でもそのままだと誤解していました。最新フロー確認し、問題ないことを確認しました。
