### ISSUE TITLE
id translation resource file translation (see MultilingualResources) 

### ISSUE THREAD

**Issue by rezafaisal** [Covid-19Radar/Covid19Radar#239]
This is Indonesia translation resource file 

[Covid19Radar.id.zip](https://github.com/Covid-19Radar/Covid19Radar/files/4654827/Covid19Radar.id.zip)

**Comment by changeworld** [comment]
@rezafaisal 
Thank you for contributing!

**Comment by rezafaisal** [comment]
@changeworld はい, お疲れ様です
