### ISSUE TITLE
Build break in Covid19Radar.Model.UserDataModel

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#253]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Fetch latest code
Build Coivd19Radar.Android

### Any log messages given by the failure
>

### Expected/desired behavior
>
Build OK

### OS and Version?
Nexus 7(2013), Android 6.0.1
commit 7d38b524

### Mention any other details that might be useful
Please fix follows:
Covid19Radar.Model.UserDataModel:
using Covid19Radar.Api.Common;
  ->
using Covid19Radar.Common;

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by changeworld** [comment]
@oyasan-ba2
ご指摘ありがとうございました。
修正しました。
