### ISSUE TITLE
多言語対応部分に不一致が存在する

### ISSUE THREAD

**Issue by changeworld** [Covid-19Radar/Covid19Radar#258]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> None

### Any log messages given by the failure
> None

### Expected/desired behavior
> None

### OS and Version?
> None

### Mention any other details that might be useful

多言語アプリ ツールキットの参照するPathが間違っていた。
その状態で、多言語対応開発を進めていた結果

* Covid19Radar.xx.xlf 側に定義されていないが、AppResources.resx には定義されている（ので言語毎に動的に動作できる）
* AppResources.xx.resx 側に定義されていないが、Covid19Radar.xx.xlf 側に定義されている（動作的に使われていないTerm）

という状態になっていた。

多言語アプリ ツールキットの参照するPathを適切な状態にした結果

AppResources.resx -> Covid19Radar.xx.xlf -> AppResources.xx.resx という自動生成をビルド時に行うと、AppResources.xx.resx の定義が欠落してしまう状態になっている。

### 解決策

* AppResources.resx
* AppResources.xx.resx (主に ja )

の定義を比較し、AppResources.resx を適切な定義を持つ状態に修正し、その後に自動生成を行い、多言語対応を適切な状態にする。

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by oyasan-ba2** [comment]
指摘が通じたようでよかったです :-)

**Comment by oyasan-ba2** [comment]
3回目の指摘です。 in AppResources.resx
DescriptionPageTextStep1Description2: SimpleText
DescriptionPageTextStep2Description2: SimpeText
に正しい英文を入れて(AppResources.en.resxではなく)、自動翻訳しないと、翻訳結果が各言語Resources: AppResources.*f.resx に反映されていないように見えています。
(現在は、"SimpleText"の自動翻訳結果が入っている)

**Comment by oyasan-ba2** [comment]
DescriptionPageTextStep1Description2: SimpleText
DescriptionPageTextStep2Description2: SimpeText
が使われていないのに存在するだけかも。
よくわからないのは、上記は、en, ja には存在しないが、ほかの言語ファイルには存在することです。
