### ISSUE TITLE
Unhandled Exception when app of Release build lunch

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#262]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Install the latest app in App Center
Lunch app
Display "Unhandled Exception occurs" and exit application

### Any log messages given by the failure
>
05-22 05:25:22.906 E/AppCenterCrashes(19823): Unhandled Exception from source=AppDomain
05-22 05:25:22.906 E/AppCenterCrashes(19823): Java.Lang.IllegalStateException: Nonexistent connection status for service config: com.google.android.gms.nearby.exposurenotification.START
05-22 05:25:22.906 E/AppCenterCrashes(19823):   --- End of managed Java.Lang.IllegalStateException stack trace ---
05-22 05:25:22.906 E/AppCenterCrashes(19823): java.lang.IllegalStateException: Nonexistent connection status for service config: com.google.android.gms.nearby.exposurenotification.START
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.common.internal.zze.zzb(com.google.android.gms:play-services-basement@@17.1.0:34)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.common.internal.GmsClientSupervisor.zza(com.google.android.gms:play-services-basement@@17.1.0:11)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.common.internal.BaseGmsClient.zza(com.google.android.gms:play-services-basement@@17.1.0:124)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.common.internal.BaseGmsClient.zza(com.google.android.gms:play-services-basement@@17.1.0:358)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.common.internal.BaseGmsClient$zza.zza(com.google.android.gms:play-services-basement@@17.1.0:21)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.common.internal.BaseGmsClient$zzb.zzo(com.google.android.gms:play-services-basement@@17.1.0:11)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.common.internal.BaseGmsClient$zzc.handleMessage(com.google.android.gms:play-services-basement@@17.1.0:49)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at android.os.Handler.dispatchMessage(Handler.java:102)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at com.google.android.gms.internal.common.zzi.dispatchMessage(com.google.android.gms:play-services-basement@@17.1.0:8)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at android.os.Looper.loop(Looper.java:148)
05-22 05:25:22.906 E/AppCenterCrashes(19823): 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-22 05:25:22.929 W/ActivityManager(  602): Launch timeout has expired, giving up wake lock!

### Expected/desired behavior
>
Lunch app successfully

### OS and Version?
Nexus 7(2013), Android 6.0.1
Covid19RadarAndroid 1.0 (319)

### Mention any other details that might be useful
Please refer Exposure Notifications API: Android Reference Design
https://github.com/google/exposure-notifications-android

**Comment by oyasan-ba2** [comment]
すみません。下記で引っかかっていました
05-22 05:25:22.788 W/ExposureNotification(23785): Reject the api access due to the caller is not whitelisted [CONTEXT service_id=236 ]

**Comment by oyasan-ba2** [comment]
Confirmed this issue occurs only Release build. Debug build can run successfully without this issue.

**Comment by changeworld** [comment]
最新ソースでは対応済みです。
