### ISSUE TITLE
Build error when deploying azure function API

### ISSUE THREAD

**Issue by medboz** [Covid-19Radar/Covid19Radar#266]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>See builds in https://github.com/Covid-19Radar/Covid19Radar/actions

### Any log messages given by the failure
>MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.

### Expected/desired behavior
>Build successfully

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Invariant

### Mention any other details that might be useful

> I'm not sure if the github action is still used to build and deploy Covid19Radar API to Azure Function, but I found that builds are failing due to the error mentioned above.
> Thanks! We'll be in touch soon.

**Comment by medboz** [comment]
First fix in #267
Second fix in #272

**Comment by medboz** [comment]
@runceel Could you please help me to fix the remaining error when deploying to azure functions.

**Comment by kazumihirose** [comment]
Thank you for your PR and Code.

**Comment by medboz** [comment]
@kazumihirose you're welcome. I think there is a remaining error when deploying to azure function but I don't have enough  access right to fix it. Do you confirm that that azure function web API is used?
