### ISSUE TITLE
Build error : UpdateInfomationPage not found

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#277]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Fetch the latest master  a975ba16f917bd12de99c4b2febdb42f8f1aa537
Build

### Any log messages given by the failure

Following build error is detected:
  'UpdateInfomationPage' not found
It looks like typo: 'UpdateInformationPage'

### Expected/desired behavior

Build successfully

### OS and Version?

Android

**Comment by changeworld** [comment]
refs #278

**Comment by oyasan-ba2** [comment]
@changeworld Please also merge #280
