### ISSUE TITLE
Update iOS/Android Build status

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#301]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [] feature request
- [x] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Browse top page of this project (Covid19Radar/(README.md|README.ja.md))
Show build statuses are always red.

### Any log messages given by the failure
None

### Expected/desired behavior
Apply the real build status for iOS/Android

### OS and Version?
Any browser

### Mention any other details that might be useful
I think that previous build pipeline may be stopped.
We should update it and execute build only and show the latest status.

**Comment by changeworld** [comment]
一時的にAppCenterのビルドを止めていた影響のため、クローズします。
