### ISSUE TITLE
How to run App Center Test on iPhone with iOS 13.5

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#302]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Build and run Automatic test of this app for iPhone on iOS 13.5

### Any log messages given by the failure
None

### Expected/desired behavior
Run Automatic test of this app for iPhone on iOS 13.5 successfully.

### OS and Version?
iOS 13.5

### Mention any other details that might be useful
How can we use iPhone on iOS 13.5 in App Center Test ?
In current support list, iOS 13.5 did not listed on it.
https://docs.microsoft.com/en-us/appcenter/test-cloud/devices

How can we proceed to discuss this issue with Azure/App Center Test of MS Japan and MS ?

**Comment by oyasan-ba2** [comment]
I believe that we should perform automatic test on following devices.
Any comments and proposals are welcome.

---
# Covid19Radar test target list
# <device> <OS> <period ("D"isable=Test manually, "N"ightly, "W"eekly, "M"onthly)> # Share in Japan (Carrier) / Manual test contributer

# Nightly
#  iPhones Top 10 in Japan(2019)
#	Ref.:	DeviceAtlas The most popular smartphones in 2019(Q2 2019)
#	        https://deviceatlas.com/blog/most-popular-smartphones#japan
Apple iPhone 7			13.5	N	# 11.73% (All)
Apple iPhone 8			13.5	N	# 11.28% (All)
Apple iPhone 6s			13.5	N	#  5.66% (All)
Apple iPhone X			13.5	N	#  5.31% (All)
Apple iPhone 7 Plus		13.5	N	#  3.69% (All)
Apple iPhone SE			13.5	N	#  3.54% (All)
Apple iPhone 8 Plus		13.5	N	#  3.35% (All)
Apple iPhone XR			13.5	N	#  3.00% (All)
# Apple iPhone 6		12.4.1(Not supported)          	#  2.99% (All)
Apple iPhone XS			13.5	N	#  2.89% (All)
---

**Comment by kazumihirose** [comment]
Currently, the general public does not have these tests.
This is due to Apple's restrictions.
Please understand and Thank you for your kindness.

**Comment by oyasan-ba2** [comment]
Thank you for your reply and information. I understood your situation.
