### ISSUE TITLE
Multilingual localization for release

### ISSUE THREAD

**Issue by changeworld** [Covid-19Radar/Covid19Radar#313]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

ViewModels

- HomePage
  - [x] ContributorsPageViewModel.cs
  - [x] DebugPageViewModel.cs
  - [x] ExposuresPageViewModel.cs
  - [ ] HomePageViewModel.cs
  - [x] LicenseAgreementPageViewModel.cs
  - [x] NotifyOtherPageViewModel.cs
  - [x] SettingsPageViewModel.cs
  - [x] ~SharePositiveDiagnosisPageViewModel.cs~
  - [x] UpdateInformationPageViewModel.cs
- Tutorial
  - [x] DescriptionPage1ViewModel.cs
  - [x] DescriptionPage2ViewModel.cs
  - [x] DescriptionPage3ViewModel.cs
  - [x] DescriptionPage4ViewModel.cs
  - [ ] InitSettingPageViewModel.cs
  - [x] PrivacyPolicyPageViewModel.cs
  - [x] SetupCompletedPageViewModel.cs
  - [x] StartTutorialPageViewModel.cs
- [x] ExceptionPageViewModel.cs
- [x] MenuPageViewModel.cs
- [x] ViewModelBase.cs

Views
- HomePage
  - [x] ContributorsPage.xaml
  - [x] ContributorsPage.xaml.cs
  - [x] DebugPage.xaml
  - [x] DebugPage.xaml.cs
  - [ ] ExposuresPage.xaml
  - [x] ExposuresPage.xaml.cs
  - [ ] HomePage.xaml
  - [x] HomePage.xaml.cs
  - [x] LicenseAgreementPage.xaml
  - [x] LicenseAgreementPage.xaml.cs
  - [ ] NotifyOtherPage.xaml
  - [x] NotifyOtherPage.xaml.cs
  - [x] SettingsPage.xaml
  - [x] SettingsPage.xaml.cs
  - [x] ~SharePositiveDiagnosisPage.xaml~
  - [x] ~SharePositiveDiagnosisPage.xaml.cs~
  - [x] UpdateInformationPage.xaml
  - [x] UpdateInformationPage.xaml.cs
- Tutorial
  - [x] DescriptionPage1.xaml
  - [x] DescriptionPage1.xaml.cs
  - [x] DescriptionPage2.xaml
  - [x] DescriptionPage2.xaml.cs
  - [x] DescriptionPage3.xaml
  - [x] DescriptionPage3.xaml.cs
  - [x] DescriptionPage4.xaml
  - [x] DescriptionPage4.xaml.cs
  - [x] InitSettingPage.xaml
  - [x] InitSettingPage.xaml.cs
  - [x] PrivacyPolicyPage.xaml
  - [x] PrivacyPolicyPage.xaml.cs
  - [x] SetupCompletedPage.xaml
  - [x] SetupCompletedPage.xaml.cs
  - [x] StartTutorialPage.xaml
  - [x] StartTutorialPage.xaml.cs
- [x] ExceptionPage.xaml
- [x] ExceptionPage.xaml.cs
- [x] MenuPage.xaml
- [x] MenuPage.xaml.cs

**Comment by oyasan-ba2** [comment]
@changeworld Could you please also check and apply needed changes #327 ?
