### ISSUE TITLE
The contribute instructions are way too unclear

### ISSUE THREAD

**Issue by csleead** [Covid-19Radar/Covid19Radar#32]
I found this project meaningful and want to see what can I help with.
However, the instructions are so unclear that I have no idea what I can do.

- We can't add Todo items to [Project Feature](https://github.com/Covid-19Radar/Covid19Radar/projects/1). How can we make suggestions?
- How do we know which todo items are the ones we should work with?
- The todo items lack detailed descriptions.

For outside contributors like me to help, some improvement must be made about this.

**Comment by kazumihirose** [comment]
Thank you, I am currently preparing TODO for Issue.
Please give me some more time.
