### ISSUE TITLE
Review the translation of Chinese

### ISSUE THREAD

**Issue by wangmengyucca** [Covid-19Radar/Covid19Radar#327]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
win10

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

[Covid19Radar.zh-Hans.zip](https://github.com/Covid-19Radar/Covid19Radar/files/4701338/Covid19Radar.zh-Hans.zip)

**Comment by changeworld** [comment]
@wangmengyucca 
Thank you for contributing!
