### ISSUE TITLE
Fix new app name on Android

### ISSUE THREAD

**Issue by oyasan-ba2** [Covid-19Radar/Covid19Radar#374]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Build Covid19Radar.Android
Start debugging above

### Any log messages given by the failure
None

### Expected/desired behavior
Show new app name on Android Home (currently old name is displayed)

### OS and Version?
Nexus 7(2013), Android 6.0.1

**Comment by changeworld** [comment]
名前が異なるのでクローズします。
