### ISSUE TITLE
fr translation resource file translation (see MultilingualResources)

### ISSUE THREAD

**Issue by kazumihirose** [Covid-19Radar/Covid19Radar#38]
fr translation resource file translation (see MultilingualResources)
XLIFF Files transration

**Comment by xinity** [comment]
One way to translate in fr :-)
Expected branch and PR within few hours :-)

Love the idea and the project, kudos folks 👏 👏 👏 👏

**Comment by xinity** [comment]
see #204 .
Hoping this would help :)

Let me know,

Cheers!
