### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by HIBIKI-CUBE** [Covid-19Radar/Covid19Radar#450]
App crashes when the COVID-19 Exposure Logging is turned off.

**Steps to reproduce the behavior:** (iOS)
1. Open settings and go to Privacy > Healthcare > COVID-19 Exposure Logging
2. Turn the switch off.
3. Launch the app.
4. App crashes immediately.

**Expected behavior**
Launch normally and show that this app won't work without turning on the switch.

**Screenshots**
https://twitter.com/blue_kanikama/status/1273871208493154304?s=21

**Device info:**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.6 Public Beta
 - Location: Yokohama, Japan
 - System region: Japan
 - Apple ID region: Japan
 - Version: 1.0.0

**Comment by treastrain** [comment]
I have the same problem.

- Device: iPhone 11 Pro (A2215, MWCC2J/A)
- OS: iOS 13.5.1 (17F80)
- Location: Muroran, Hokkaido Pref., Japan
- System region: Japan
- System Language: Japanese
- Apple ID region: Japan
- Version 1.0.0

**Comment by changeworld** [comment]
same problem.

https://twitter.com/fmht7/status/1273967247845777409

**Comment by kazumihirose** [comment]
おそらく、初回でOS側で拒否扱いなると、その後他のENアプリを入れないと有効にできないってやつだと思う。（アプリからOSのステートを変えられない問題、ちょっと対応策考えます。）

**Comment by laiso** [comment]
たしかに一度設定された権限系のステートはアプリ側から再要求する仕組みがないのですよね……

対策としては [OpenSettingsUrlString](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiapplication.opensettingsurlstring?view=xamarin-ios-sdk-12) を使って該当設定を開かせ、変更を促すようなアプリが多いです
(Google Mapsで位置情報取得を拒否している時のような動作)

**Comment by HIBIKI-CUBE** [comment]
現状以下の症状をTwitter上で確認しています。

**初期ダイアログで拒否**
-> APIが有効にならない。承認済みのAppとして表示されない。再インストールなどを繰り返すと改善する場合あり

**初期ダイアログで許可し、後ほどスイッチをオフ**
-> クラッシュするが再度オンにすれば解消する

**Comment by shotantan** [comment]
same.

Device: iPhone 8 (MX1E2J/A)
OS: iOS 13.5.1 (17F80)
Location: Tokyo, Japan
System region: Japan
System Language: Japanese
Apple ID region: Japan
Version 1.0.0

I also tried re-install. But nothing has been change.

**Comment by HIBIKI-CUBE** [comment]
v 1.1.1において不具合が修正されていることが確認できました。
インストール時に許可をしなかった場合の挙動は確認できていません
![Uploading 86095668...]()

**Comment by treastrain** [comment]
私の以下の環境でも App Store 版 バージョン1.1.1 にて問題が解決されたことを確認しました。

- Device: iPhone X (A1902, MQAY2J/A)
- OS: iOS 13.5.1 (17F80)
- Location: Muroran, Hokkaido Pref., Japan
- System region: Japan
- System Language: English
- Apple ID region: Japan
- Version 1.1.1

なお、私の初出のコメント https://github.com/Covid-19Radar/Covid19Radar/issues/450#issuecomment-646484279 で示した iPhone 11 Pro (A2215, MWCC2J/A) は iOS 14 beta (18A5301v) にアップデートしてしまったため、検証を行うことができませんが、App Store 版 1.0.0 ではそもそもアプリが起動しない問題がありました。その問題も App Store 版 1.1.1 で解消されていることを合わせて報告します（iOS 14 beta (18A5301v) では ExposureNotification は本コメント投稿時点で使用不可能なため、Logging は有効にできません）。
