### ISSUE TITLE
新しい生活様式 (atarashii_seikatsu) is deprecated

### ISSUE THREAD

**Issue by muojp** [Covid-19Radar/Covid19Radar#458]
**Describe the bug**

新しい生活様式 (atarashii_seikatsu) shown in the app is deprecated.

![image](https://user-images.githubusercontent.com/766864/85127973-655c1600-b26b-11ea-9858-861f1c1cc48f.png)

It seems that the MHLW guideline was updated at 6/19/2020. It contains a major difference. '外出控え' (avoid unnecessary outgoing) is now diminished.

Current version:
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_newlifestyle.html
https://www.mhlw.go.jp/content/10900000/000641743.pdf
![image](https://user-images.githubusercontent.com/766864/85127808-17dfa900-b26b-11ea-92bb-4206c94fc7f1.png)

Deprecated version:
Ref:
http://web.archive.org/web/20200615225342/https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_newlifestyle.html
(PDF cache is also available: http://web.archive.org/web/20200604113839/https://www.mhlw.go.jp/content/10900000/000635643.pdf )
![image](https://user-images.githubusercontent.com/766864/85127852-26c65b80-b26b-11ea-89fa-a1b7bd64a4a0.png)

**To Reproduce**
1. Tap on '陽性者との接触を確認する'

**Expected behavior**
Show the latest guidelines.

**Smartphone (please complete the following information):**
 - Device: Galaxy Z Flip
 - OS: Android 10
 - Browser N/A
 - Version 1.0.0

**Comment by muojp** [comment]
Updating series of 'Nocontact10.png' files (e.g. https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar.Android/Resources/drawable-ja-xxxhdpi/Nocontact10.png ) would be enough.

**Comment by kazumihirose** [comment]
本件はアプリの仕様によるところになりますので、いったん保留とさせてください。

**Comment by shogo82148** [comment]
本プロジェクトの全体像を把握できておらず恐縮なのですが、「アプリの仕様」はどこかで確認可能でしょうか？

COCOAの関連ページをかんたんに探してみましたが、以下の資料しか見つけることができませんでした。
資料の中には「新しい生活様式 」についての言及はありません。

- [接触確認アプリに関する仕様書等の公表](https://cio.go.jp/node/2613)
- [資料１： 接触確認アプリ及び関連システム仕様書](https://cio.go.jp/sites/default/files/uploads/documents/techteam_20200526_02.pdf)
- [資料２： 「接触確認アプリ及び関連システム仕様書」に対するプライバシー
及びセキュリティ上の評価及びシステム運用留意事項](https://cio.go.jp/sites/default/files/uploads/documents/techteam_20200526_02.pdf)

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。

**Comment by muojp** [comment]
対応ありがとうございました。厚生労働省のCOCOA問い合わせ窓口へのメール連絡が推奨コンタクト手段のようでしたので、そちらへ本issueのリンクも添えて現象報告しました。
