### ISSUE TITLE
'Privacy Policy' screen skipping

### ISSUE THREAD

**Issue by nezuku** [Covid-19Radar/Covid19Radar#459]
**Describe the bug**
A user can skip 'Privacy Policy' screen.

**To Reproduce**
1. Open the app.
2. Tap ’I accept the Terms of Use' on 'Term of Use' screen.
3. Stop the app by a task switcher on 'Privacy Policy' screen.
4. Open the app again.
5. The app shows a main screen without agree to a privacy policy.

**Expected behavior**
To use the app, a user have to agree to a privacy policy.

**Screenshots**
I taken a screen recording for this issue.
https://twitter.com/nezuku/status/1273990199198928896/video/1

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 10 (Build QQ3A.200606.001)
 - Version 1.0

**Additional context**
I hear/saw same bug happens on the iOS version at Twitter.
https://twitter.com/NStyles/status/1273869658370629632

**Comment by nezuku** [comment]
I add a link to the Tweet that shows this issue by a screen recording.

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
