### ISSUE TITLE
Wrong link in "Support"(アプリに関するお問い合わせ)

### ISSUE THREAD

**Issue by taichanNE30** [Covid-19Radar/Covid19Radar#460]
**Describe the bug**
FAQ link in Support is broken.

**To Reproduce**
1. Go to 'Support'
2. Click on 'FAQ'（新型コロナウイルス感染症対策サイト） link
3. The link is broken.

**Expected behavior**
Should show some info page.

**Screenshots**
![IMG_0371](https://user-images.githubusercontent.com/40626578/85132233-4feaea00-b273-11ea-9441-f85af0032394.PNG)
![IMG_0370](https://user-images.githubusercontent.com/40626578/85132006-eb2f8f80-b272-11ea-8642-0b37e626947b.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 13.0
 - Version 1.0.0

**Additional context**

**Comment by taichanNE30** [comment]
I misunderstand that this application is same app as the app on the appstore.
If the issue isn’t related on this (original) app.
Please close this issue.

**Comment by shinriyo** [comment]
It is already fix.

**Comment by changeworld** [comment]
fix https://github.com/Covid-19Radar/Covid19Radar/commit/955c268c434e4e75c7358c2d0a2b53fd29b87804
