### ISSUE TITLE
Scrolling problem in privacy policy

### ISSUE THREAD

**Issue by nmisawa** [Covid-19Radar/Covid19Radar#463]
**To Reproduce**
1. select the privacy policy from the menu
2. scroll through the text.
3. blank scrolling continues past the body text.

**Expected behavior**
I don't think the scrolling area matches the height of the text.

**Screenshots**
![IMG_1193](https://user-images.githubusercontent.com/1043573/85134015-c1786780-b276-11ea-8798-4ccf03bf500c.PNG)

**Smartphone (please complete the following information):**
 - iPhone 11 Pro
 - iOS13.5

**Comment by uhooi** [comment]
Android版は再現しませんでした。
また、プライバシーポリシーのほかに利用規約も同様でした。

**Comment by inouekoji** [comment]
次の環境しかもっておりませんが、プライバシーポリシーは同じ現象が出ます。
利用規約については、当方は発生しませんでした。

* iPhone X, iOS 13.5.1
* iPhone SE(第2世代), iOS 13.5.1

**Comment by uhooi** [comment]
失礼しました。
利用規約は初回チュートリアルのみで発生し、メニューからの遷移時は発生しませんでした。

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
