### ISSUE TITLE
Can't send an inquiry email from Gmail.

### ISSUE THREAD

**Issue by nmisawa** [Covid-19Radar/Covid19Radar#464]
**To Reproduce**
When I try to send a Gmail message to an email address listed in the FAQ, it fails to send.
I can send it from the iOS Mail app.

**Screenshots**
<img width="500" alt="スクリーンショット 2020-06-19 21 24 17" src="https://user-images.githubusercontent.com/1043573/85134486-8c204980-b277-11ea-8793-46a131a6bf1d.png">

**Desktop (please complete the following information):**
 - macOS
 - Chrome/Safari

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
