### ISSUE TITLE
途中のダイアログで「有効にしない」を選んだらアプリを起動できずに落ちる挙動を繰り返すようになった

### ISSUE THREAD

**Issue by Cat-sushi** [Covid-19Radar/Covid19Radar#465]
主題の報告が下記に有ります

https://twitter.com/fmht7/status/1273967247845777409

**Comment by su8ru** [comment]
# Duplicate of #450 

I don't have the permission to close this, so I suggest you close it yourself.
Then why don't you add a comment to #450?

**Comment by changeworld** [comment]
@Cat-sushi 
指摘ありがとうございます。
#450 と重複しているので、そちらに追記してこちらはクローズします。
