### ISSUE TITLE
English translation of "submit consent" is very difficult to understand

### ISSUE THREAD

**Issue by dkastl** [Covid-19Radar/Covid19Radar#469]
**Describe the bug**

The English version of the "submit consent page" is very difficult to understand at the beginning, and not understandable at all in the last paragraph. 

**To Reproduce**
1. Open the app
2. Go to the "consent submission" screen

**Expected behavior**

Understandable explanation.

**Screenshots**

![Screenshot_2020-06-19-19-45-56-299_jp go mhlw covid19radar](https://user-images.githubusercontent.com/227762/85145859-29837980-b288-11ea-8cbb-206c5b074564.jpg)

**Smartphone (please complete the following information):**
 - OS:Android 10

**Additional context**

It seems that English was used as the `source` language in the localization process, but lots of strings were machine translated from Japanese. I'm wondering if the localization to other languages was done correctly based on the English source.

I'm not sure, if changes to English also require an update to the `source`, because this would apply then to all other language files as well.

**Comment by Queen-esther01** [comment]
Okay, so basically a simpler English version is needed. Please what's the link to the app, I want to check out the full submit consent section.
