### ISSUE TITLE
Browsing any websites with the privacy policy screen.

### ISSUE THREAD

**Issue by piyokango** [Covid-19Radar/Covid19Radar#475]
**Describe the bug**
A user can browse any websites with the privacy policy screen.

**To Reproduce**
1. Open the app.
2. Tap Privacy Policy from the menu.
3. Tap the hyperlink "ウェブサイト" in the text.
4. Browse any websites by following the link of the mhlw website.

**Expected behavior**
disable the hyperlink on privacy policy.

**Screenshots**
I taken a screen recording for this issue.
https://twitter.com/piyokango/status/1274042139551207424

**Device**
 - Device: iPhone 7
 - iOS 13.5.1

**Comment by kazumihirose** [comment]
Thank you for good suggestion, Included in the time release version.

**Comment by sergioya** [comment]
If this app uses SFSafariView api, I don’t see this is an issue.

**Comment by kazumihirose** [comment]
Thank you for contribute, this is fixed.
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
