### ISSUE TITLE
Registeration with the changed date

### ISSUE THREAD

**Issue by piyokango** [Covid-19Radar/Covid19Radar#477]
**Describe the bug**
A user can register with the changed system date.

**To Reproduce**
1. Install the app.
2. Change system date on OS.
3. Register the app.
4. The Changed date is displayed on the home screen.

**Expected behavior**
check date before registration.

**Screenshots**
I taken a screen shot for this issue.
https://twitter.com/piyokango/status/1274073121968934913

**Device**
 - Android 9

**Comment by kuramochia** [comment]
Already fixed at #442
