### ISSUE TITLE
Line breaks(\r\n) not works in a mail app

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#479]
**Describe the bug**
Line breaks(\r\n) are printed as characters.

**To Reproduce**
1. Go to 'App Settings'
2. Click on 'appsupport@cov19.mhlw.go.jp'

**Expected behavior**
Mail body is shown as below.
```
お名前：
ご連絡先：
お問い合わせ内容(カテゴリを次の中からお選びください)：1.アプリの仕組み、2.アプリの設定、 3.アプリの利用(通知など)、 4.その他
お問い合わせ本文：

```

**Screenshots**
![Screenshot_20200620-100353~2](https://user-images.githubusercontent.com/30116202/85188231-10a6b280-b2e0-11ea-8f95-b2712166431e.jpg)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 11 Beta
 - Browser: Chrome 83.0.4103.106
 - Mail client: Gmail  2020.05.17.313130447.Release
 - App Version: 1.0.0(From Google Play Store)

**Additional context**
* If substitute the value of AppResources.InqueryMailBody for mail body directory(e.g. body = "お名前：\r\nご連絡先..."), this issue is not confirmed.
* **It seems that line breaks have been escaped(\r\n → \\\\r\\\\n) in ResourceManager.GetString(...), so it is able to fix like AppResources.InqueryMailBody.Replace("\\\\r\\\\n", "\r\n")**

**Comment by testedquality** [comment]
My device will be in the same state.
- Device: HUAWEI P10 lite
- OS: Android 8.0

**Comment by laiso** [comment]
my workaround but it should have to resolve by translating from a language source.

```
diff --git a/Covid19Radar/Covid19Radar/ViewModels/HelpPage/InqueryPageViewModel.cs b/Covid19Radar/Covid19Radar/ViewModels/HelpPage/InqueryPageViewModel.cs
index 8b482ce7..e7491214 100644
--- a/Covid19Radar/Covid19Radar/ViewModels/HelpPage/InqueryPageViewModel.cs
+++ b/Covid19Radar/Covid19Radar/ViewModels/HelpPage/InqueryPageViewModel.cs
@@ -52,7 +52,7 @@ namespace Covid19Radar.ViewModels
                 var message = new EmailMessage
                 {
                     Subject = AppResources.InqueryMailSubject,
-                    Body = AppResources.InqueryMailBody,
+                    Body = AppResources.InqueryMailBody.Replace("\\r\\n", "\r\n"),
                     To = recipients
                 };
                 await Email.ComposeAsync(message);
```

**Comment by kazumihirose** [comment]
Thank you for good suggestion.
We will replace language files text.
