### ISSUE TITLE
A typo "電話場号" exist in "What is a 'close contact'?" screen.

### ISSUE THREAD

**Issue by nano-nano** [Covid-19Radar/Covid19Radar#480]
**Describe the bug**
A typo "電話場号" exist in "What is a 'close contact'?"(接触の記録方法) screen.

**To Reproduce**

1. Launch the app.
2. Tap "How to use"(使い方)
3. Tap "What is a 'close contact'?"(どのようにして接触を記録していますか？)

**Expected behavior**
Show "電話番号" in message instead of "電話場号"

**Screenshots**
![Screenshot_20200620-104102](https://user-images.githubusercontent.com/29051777/85188897-105ce600-b2e5-11ea-90b3-2f98e18bce7b.png)

**Smartphone (please complete the following information):**
- Device: Xperia XZ3(Android 10)
- App Version: 1.0.0(from Google Play)

**Comment by changeworld** [comment]
#454 で対応済みですので、次期リリースで対応版がリリースされます。
