### ISSUE TITLE
Android プロジェクトでビルドエラー「already defined with incompatible format.」が発生します/Build failed in Android Project

### ISSUE THREAD

**Issue by amay077** [Covid-19Radar/Covid19Radar#495]
**Describe the bug**
Covid19Radar.Android プロジェクトでビルドエラー「Attribute "imageAspectRatioAdjust" already defined with incompatible format.」等が発生します。
Build error "Attribute "imageAspectRatioAdjust" already defined with incompatible format." occurs in Covid19Radar.Android project.

**To Reproduce**
1. Clean nuget cache (Delete ``%userprofile%\.nuget\packages`` directory)
2. Clean solution (Delete ``bin/``, ``obj/`` dir in each projects and root ``.vs/`` dir)
3. Clone [latest code (c9a2ae55968ba8a954f3fef00a48039beaf019da)](https://github.com/Covid-19Radar/Covid19Radar/tree/c9a2ae55968ba8a954f3fef00a48039beaf019da). 
4. Open ``Covid19Radar.sln`` with Visual Studio 2019
5. Change configuration / platform to Debug / Any CPU
6. Change Startup project to ``Covid19Radar.Android``
7. Start Debugging with any android phone/emulator
8. Wait for few minutes.... show "build failed" and below errors.

```
2>------ Build started: Project: Covid19Radar.Android, Configuration: Local Any CPU ------
2>Covid19Radar\Covid19Radar.Android\obj\Local\100\lp\69\jl\res\values\values.xml(35): error APT1000: Attribute "imageAspectRatioAdjust" already defined with incompatible format.
2>Covid19Radar\Covid19Radar.Android\obj\Local\100\lp\119\jl\res\values\values.xml(36): error APT1000: Original attribute defined here.
2>Covid19Radar\Covid19Radar.Android\obj\Local\100\lp\69\jl\res\values\values.xml(48): error APT1000: Attribute "buttonSize" already defined with incompatible format.
2>Covid19Radar\Covid19Radar.Android\obj\Local\100\lp\119\jl\res\values\values.xml(49): error APT1000: Original attribute defined here.
2>Covid19Radar\Covid19Radar.Android\obj\Local\100\lp\69\jl\res\values\values.xml(56): error APT1000: Attribute "colorScheme" already defined with incompatible format.
2>Covid19Radar\Covid19Radar.Android\obj\Local\100\lp\119\jl\res\values\values.xml(57): error APT1000: Original attribute defined here.
```

**Expected behavior**

build success.

**Screenshots**

![image](https://user-images.githubusercontent.com/401369/85197657-69487080-b31d-11ea-8ec4-27d7f9f42361.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Additional context**

最新の VS2019 や Xamarin/Android SDK を使用しているつもりです。Visual Studio 2019 info を添付します。
I am using latest VS2019 and xamarin/android sdks. Attaching to my Visual Studio 2019 info.

- [vs_info.txt](https://github.com/Covid-19Radar/Covid19Radar/files/4807588/vs_info.txt)

**Comment by Aqua-ix** [comment]
私の環境では、
Covid19Reader.Android/Properties 
の 
`Use incremental Android packaging system (aap2)`
をアクティブにしたところビルドが通るようになりました。
![image](https://user-images.githubusercontent.com/29789286/85198005-16bc8380-b320-11ea-94ef-a45b53449afb.png)

**Comment by amay077** [comment]
@Aqua-ix さんありがとうございます。

おっしゃる通り、

``Covid19Radar\Covid19Radar.Android\Covid19Radar.Android.csproj`` で``<AndroidUseAapt2>false</AndroidUseAapt2>``
であるとビルドエラーになるようです（上記オプションを入れると ``true`` になる）。

Configuration Manager で、Debug - Android Proj では ``Local`` が使われており、Local では aapt2 が false になっているようです。

![image](https://user-images.githubusercontent.com/401369/85198038-61d69680-b320-11ea-90a6-090dc48b9057.png)

こちらのマッピングを他と同じように Debug にすることでも解決しますが、Local であることに理由がなにかあるでしょうか？ > @kazumihirose さん

**Comment by kazumihirose** [comment]
いえ、特にないと思います。最近のアップデートした後から出てまして、aap入れて直した感じです。
あと、開発環境について、ドキュメント間に合ってなくてごめんなさい。

1. MUI拡張入れてください。
https://marketplace.visualstudio.com/items?itemName=MultilingualAppToolkit.MultilingualAppToolkit-18308

2.実機で動作させる敷居が非常に高いです。
Androidでは、google playアカウントのみでデバッグ動作します。
そこで、app.xaml.csにモックアップを用意しています。アンコメントしてビルドしてください。
各画面はモックアップ切り替え後に、app.xaml.csで工夫してもらえると助かります。

3.Debugサーバ用意しますが、もう少し待ってください。
src以下にAzure Fucntionsでのソースがあります、ローカルになりますがこちらでも動作可能です。

**Comment by amay077** [comment]
> いえ、特にないと思います。
ありがとうございます。
では Debug に戻しますね。
Local であることでデバッグ実行でのブレークポイントが効かなくなっているようでもあります。

開発環境まわりは探り探りでやっています。
お手伝いできるところがあればしていきたいと思います。
