### ISSUE TITLE
Androidプロジェクト内のcsファイルに不要なインポート文が含まれている

### ISSUE THREAD

**Issue by LeoAndo** [Covid-19Radar/Covid19Radar#500]
Androidプロジェクト内のcsファイルに不要なインポート文が含まれているので削除したい

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも検討したいと思います。
