### ISSUE TITLE
Crashing in Android sub user profile

### ISSUE THREAD

**Issue by dmikurube** [Covid-19Radar/Covid19Radar#501]
**Describe the bug**

It looks that the app continues to fail if the app is running in Android's sub **"user"** profile.
Android multi-user: https://source.android.com/devices/tech/admin/multi-user

Although I've not confirmed that the sub user profile is the 100% cause, but I confirmed :
* It is working fine in my Pixel 3 in the main user of the device.
* It crashes in a sub user of the same device.

**To Reproduce**

1. Switch to a sub user (or create a sub user) on Android.
2. Install the app from Google Play Store.
3. Start the app.
4. Follow the initial steps of the app.
5. In the end of the initial steps, after the step of "activating" Bluetooth, the app crashes.
6. Once it crashes, it crashes whenever starting the app.

**Expected behavior**

In Android, sub users may not have the permission to access the Contact Tracing API. (See the screenshots below. A sub user does not have `COVID-19 （新型コロナウイルス感染症）の濃厚接触の可能性の通知` in "Settings > Google".)

If so, it should be fine that the app does not work there. But, it should not crash. One of possible options is to show a dialog to show the app does not work in a sub user, and terminate successfully, for example.

**Screenshots**

* Crashing
![Screenshot](https://user-images.githubusercontent.com/723722/85200768-167ab300-b335-11ea-9750-c058e2b12508.png)

* "Settings > Google" in a main user
![Main-user](https://user-images.githubusercontent.com/723722/85201031-0d8ae100-b337-11ea-90a3-5aa7f93dc1f8.png)

* "Settings > Google" in a sub user
![Sub-user](https://user-images.githubusercontent.com/723722/85201036-1a0f3980-b337-11ea-976d-cb45557f6327.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3
 - OS: Android 10 (Build: QQ3A.200605.001)

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
