### ISSUE TITLE
「接触の検出」の ON/OFF が反映されない

### ISSUE THREAD

**Issue by hiroto7** [Covid-19Radar/Covid19Radar#504]
**Describe the bug**
OSのポップアップ（図1）で「ONにする」を押しても、アプリの設定の「接触の検出」のON/OFFに反映されない（図2）

**To Reproduce**
1. 「アプリの設定」画面で「接触の検出」をOFFにする
2. アプリを再起動する
3. 図1のポップアップが表示されるので、「ONにする」を押す
4. 「アプリの設定」画面の「接触の検出」がONになっていない（OFFのままである、図2）

**Expected behavior**
4のとき、「接触の検出」がONになっている

**Screenshots**
図1:
![14066](https://user-images.githubusercontent.com/32275337/85202515-d4a43980-b341-11ea-8464-628a7ab3582c.png)

図2:
![14067](https://user-images.githubusercontent.com/32275337/85202519-d968ed80-b341-11ea-9b32-67f38991060c.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10
 - Browser: Chrome
 - Version: 1.0.0

**Additional context**
#450 と関連する問題かもしれません

**Comment by akashima** [comment]
Both iOS and Android are occurring regardless of app restart.
Also, it has no relation to on at startup, and it is a problem of status control and saving.
Control is not done properly.

![イメージ-2](https://user-images.githubusercontent.com/3690724/85204951-0671cc00-b353-11ea-99a7-679c5c39223f.gif)

**Comment by hiroto7** [comment]
Ver 1.1.1 にて，アプリの設定の「接触の検出」は削除されましたので，本 Issue の問題は発生しなくなりました。
こちらはクローズさせていただきます。
