### ISSUE TITLE
トップ画面の利用開始日表示が常に今日の日付になる

### ISSUE THREAD

**Issue by karmactonics** [Covid-19Radar/Covid19Radar#506]
トップ画面の「〜から使用中」の日付が、実際に利用開始した日ではなく今日の日付を表示しています
端末の日付を変えたらその日付になります
iOS版です
![F6870A50-8EAB-4A4C-AF60-F61F537F507F](https://user-images.githubusercontent.com/8557013/85203104-3c5c8380-b346-11ea-9d88-1eec73fdd1c7.jpeg)

**Comment by Aqua-ix** [comment]
#442 で解決済かと思います
