### ISSUE TITLE
Privacy policy is not shown in some languages.

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#509]
**Describe the bug**
Privacy policy is not shown in some languages, i.e. Arabic, Russian, Bulgarian, Italian and so on.

**To Reproduce**
1. Open the privacy policy page.
2. See error

**Expected behavior**
[The privacy policy page in English](https://www.mhlw.go.jp/stf/seisakunitsuite/english_pp_00032.html) will be shown.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-06-20 at 19 38 13](https://user-images.githubusercontent.com/30116202/85203712-82b3e180-b34a-11ea-9bbc-c36aad1928e1.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 (Simulator)
 - OS: iOS 13.5.1
 - Browser safari
 - Version 1.0.0

**Additional context**
None

**Comment by kazumihirose** [comment]
Currently, only Japanese, English, and Chinese privacy policies are supported. 
Can you translate the privacy policy in other languages?

**Comment by Niccari** [comment]
I'd rather to do that, unfortunately, I can't to translate to each language because lack of ability to translate.
Instead, I think it would be better to show English as the default for each language. That way we can respond quickly at the moment and at least display the privacy policy. This would allow users to read it with copy and paste and other translation apps.

**Comment by changeworld** [comment]
@kazumihirose 
@Niccari さんから各言語のプライバシーポリシーの表示で英語サイトに変更するPRをいただきましたので、こちらはクローズします。
