### ISSUE TITLE
(Android)Convert ic_launcher.png to webp

### ISSUE THREAD

**Issue by TentaShion** [Covid-19Radar/Covid19Radar#511]
I want to reduce the image size.

I tried converting ic_launcher.png to ic_launcher.webp.
If you like, I'll convert other images as well.

## 2020/06/22 追記
下記のリンクで他の画像も差し替えてみました。
ただ変更ファイルが多くレビュー負担が大きいと思われるので、このIssue の様子を見て改めてPR していこうと考えております:bow:

諸所の作業、ありがとうございます:bow:

* https://github.com/TentaShion/Covid19Radar/tree/feature/convertHamburger
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertHeader
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertHelp
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertHome
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertInfo
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertLogo
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertNocontact
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertSplash
* https://github.com/TentaShion/Covid19Radar/tree/feature/convertTutorial

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and already fixed this issue.
