### ISSUE TITLE
Crash on second app launch

### ISSUE THREAD

**Issue by akashima** [Covid-19Radar/Covid19Radar#518]
From the second time, it has been confirmed that the application crashes under the specified conditions.

Steps to reproduce the behavior: (iOS)

Prerequisite:
Complete the first boot as usual.
Please close the application from the task once before starting the second time.

1. When the app starts, tap "Menu" repeatedly at the same timing. → Crush
2. Start the application again, tap “How to use” repeatedly at the same timing → Crush
3. Other places are "App to others", "this app is", "Registration of positive information", "app for other people", etc. →Crush

See gif for details.

Screenshots:
![イメージ-2](https://user-images.githubusercontent.com/3690724/85206628-5a35e280-b35e-11ea-9618-862d65a372d0.gif)

The menu part failed to shoot the crash, but it crashes.

Device info:

Device: iPhone Xs
OS: iOS 13.5.1
Location: Tokyo, Japan
System region: Japan
Apple ID region: Japan
Version: 1.0.0

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and already fixed this issue.
