### ISSUE TITLE
Freeze on SplashScreen with Work Profile

### ISSUE THREAD

**Issue by fumiya-kume** [Covid-19Radar/Covid19Radar#519]
**Describe the bug**

**To Reproduce**
1. enable work profile
2. launch this app
3. freeze on SplashScreen

**Expected behavior**

Launch this app or show error message.

**Screenshots**

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/16269075/85207631-cc112a80-b364-11ea-9380-71f56b0f79f9.gif)

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 10
 - Browser Google Chrome
 - Version 4 (current master beach)

**Additional context**

Work Profile information is here.
https://developer.android.com/work/managed-profiles

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and already fixed this issue.
