### ISSUE TITLE
【Android】端末の言語を英語にしてToolbarのタイトルが末尾が...になる

### ISSUE THREAD

**Issue by LeoAndo** [Covid-19Radar/Covid19Radar#523]
**Describe the bug**
端末の言語を英語にしてToolbarのタイトルが末尾が...になります

**To Reproduce**
1. Androidの設定アプリから英語を選択する
2. アプリを起動する
3. 以下の画面を開く
![Screenshot_20200620-231012](https://user-images.githubusercontent.com/16476224/85212363-e959ef00-b38c-11ea-9b30-636873fc2acf.png)

**Expected behavior**
タイトル名が...と省略されずに表示されるとみやすいと思いました。

**Screenshots**
再現手順を確認ください

**Smartphone (please complete the following information):**
 - Device: Pixcel 3 (Android)
 - OS: 10
 - Browser Chrome
 - Version 1.0

**Comment by LeoAndo** [comment]
こちら操作しての直感で思ったことになりますので、
タイトル名が...と省略されることが意図する動作であればissueクローズお願いいたします。

**Comment by changeworld** [comment]
@LeoAndo 
ご指摘ありがとうございます。
ご指摘の内容について現状対応できません。
理由として、こちらに伝えられている文言は日本語のみで、それを英語と中国語に翻訳しています。日本語の文言をベースにしたデザインなどを伝えられているため、英語や中国語の文言ではデザインと必ずしも合致せず、「…」となるケースがいくつかあります。
こちらの問題点は既にデザイン・文言を決めている方には伝達済みとなります。
