### ISSUE TITLE
【Android/iOS】開発環境構築手順のドキュメント化

### ISSUE THREAD

**Issue by LeoAndo** [Covid-19Radar/Covid19Radar#527]
@kazumihirose 

https://github.com/Covid-19Radar/Covid19Radar/issues/495#issuecomment-646970311
にて少し触れられた内容になりますが、
簡単で良いので、Windows/Macでの開発環境構築手順のドキュメント化をしていただけると嬉しいです。

**Comment by zerobase** [comment]
+1
ぜひお願いしたいです。よろしくおねがいします。

**Comment by hiroakit** [comment]
Hey guys.
Is the information you want like this?
- https://github.com/Covid-19Radar/Covid19Radar/blob/648eb021164ceeaf8197eb8846ca47adda74d436/doc/Developer.md

**Comment by zerobase** [comment]
Visual Studio for MacでiPhoneアプリをビルドできましたので情報共有しておきます。
下記の情報が「プロジェクト参加時に読むべき文書」に書かれることで、同じような点で足踏みする人がいなくなるといいですね。

全体的な手順については、このページが参考になりました：[Xamarin.iOS アプリの無料プロビジョニング - Xamarin | Microsoft Docs](https://docs.microsoft.com/ja-jp/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=macos)
ただし、Visual StudioをHomebrew Caskからインストールした場合、「Xamarin.iOSが必要」というエラーになり、ビルドできませんでした。（この原因に気づかずハマりました）
[公式サイト](https://visualstudio.microsoft.com/ja/vs/mac/)からダウンロードしてインストールすれば問題ないです。

ビルドはできたのですが、USB接続したデバイスにインストールすることはできませんでした。
code signingのための（自動生成された私の）provisioning profileには '[com.apple.developer.exposure-notification](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_exposure-notification)' というentitlementが含まれていなかったので。
このentitlementはAppleに利用申請をしなければ使えないとされています。誰でも申請すれば許可されるものでしょうか？（試していません）
entitlementを削除してビルドすることはできます。ただし、その場合はExposure Notification APIが使えなくなります。

サーバーを動かす手順はこちら https://github.com/Covid-19Radar/Covid19Radar/issues/543#issuecomment-647131802 でlaisoさんが書かれています。
ただし、[CosmosDBはMac上で動かない](https://docs.microsoft.com/ja-jp/azure/cosmos-db/local-emulator#running-on-mac-or-linux)ので、Windows仮想マシンかWindowsマシンを用意する必要があります。

**Comment by yamachu** [comment]
Exposure Notification APIは利用できませんが、
https://github.com/Covid-19Radar/Covid19Radar/pull/553
がmergeされたことにより、 `Debug_Mock` のConfigurationを使うことで、レスポンスのMockが更に容易に出来るようになったようです。

開発者の方はExposure Notification APIを使わない箇所のコントリビュートであれば `Entitlements.plist` を削除してビルドをすることでそのまま動作させることが出来そうですね。
使う場合は `Debug_Mock` のConfigurationでビルドを行いMockしたレスポンスで開発といったところでしょうか。

iOSのUSB接続での実機デプロイに関しては私は
https://docs.microsoft.com/ja-jp/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=macos
この手順を踏んだ後、Entitlements.plistを削除することでデプロイ、およびdebugを行うことが出来ました。

**Comment by hiroakit** [comment]
Hi, super geeks.

I'd add the shared information to my PR.
Azure Cosmos Emulator is cool, but why does you use it? 
It may be easier to host Azure Cosmos on your Azure.

**Comment by hiroakit** [comment]
Hey guys.

Core contributors merged #571 .
If you have any additional matters, please send your PR as well.
Thank you.

**Comment by hiroakit** [comment]
Dear @changeworld san, @kazumihirose san,

It seems that the PR merge commit (#571) has disappeared due to a something.
Should I resend a PR?

**Comment by hiroakit** [comment]
I did retry it.
Please, would do you like review #621?

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでもマージいたしました。
