### ISSUE TITLE
[Question] Is it okay to press the register button?

### ISSUE THREAD

**Issue by akashima** [Covid-19Radar/Covid19Radar#528]
I noticed that it was a preview version, so I wondered if it was okay to press the infection registration button.
Pressing the button will register with the government, so isn't false information sent to the government?
This app is a preview version, so you can press it, right?

![2292D022-B3C2-47A5-833B-EFDCE1420F95](https://user-images.githubusercontent.com/3690724/85214824-39e04500-b3ab-11ea-8057-681d23a129aa.jpeg)

**Comment by akashima** [comment]
テストとして使っても良いのであれば、

- サーバ側に送る以前にvalidationが行われているかどうか
- SQL injectionが弾かれるようになっているか
- ディレクトリトラバーサルが無効になっているか

など確認しておいて良いかと思います。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
なお、この後にHERSYSとの接続が行われて、本件はFIXされていると思われます。
