### ISSUE TITLE
エラーメッセージについて、操作内容を明記してユーザーに適切な操作を促す

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#529]
**Is your feature request related to a problem? Please describe.**
通信エラーやExposure Notificationが使えずエラーになるときにダイアログで表示されますが、現状エラー内容のみ表示されます。一般のユーザーの方にとって、特にExposure Notificationは事前知識がないため、操作内容を明示しない場合、どうすればいいか迷ってしまう可能性が高いです。

**Describe the solution you'd like**
エラー内容とともに、ユーザーにどんな操作をすべきかをメッセージで出した方がユーザーが迷いにくいのではと思います。例えば、
* Exposure Notification機能は非対応の状態です。
    * → Exposure Notification機能は非対応の状態です。OSを最新版にアップデートしてください。それでも改善しなければ、appsupport@cov19.mhlw.go.jpまでお問い合わせください。
* Exposure Notification機能は無効の状態です。
    * → Exposure Notification機能は無効の状態です。端末の設定を開いて、Exposure NotificationをONにしてください
* Connection error
    * → 通信に失敗しました。電波状況の良い場所でもう一度お試しください。

* Exposure Notificationを起動できませんでした
    * Exposure Notificationを起動できませんでした。端末の設定を開いて、Exposure NotificationをONにするとともに、BluetoothをONにしてください。
といった形です。

**Describe alternatives you've considered**
- 

**Additional context**
本内容は https://github.com/Covid-19Radar/Covid19Radar/issues/526 のメッセージに影響を与えるため、変更をする場合先にこちらの対応が必要となります。

**Comment by changeworld** [comment]
@Niccari 
ご提案ありがとうございました。対応いたします。
