### ISSUE TITLE
画面デザインの調整

### ISSUE THREAD

**Issue by amay077** [Covid-19Radar/Covid19Radar#532]
**Is your feature request related to a problem? Please describe.**

https://twitter.com/ghoul_shana/status/1273866011880550403

こちらのデザインレビューは修正検討の材料になると思います。
特にマージン、パディングのあたりは、取り掛かって問題ないと思われます。

**Comment by T-taku** [comment]
![image](https://user-images.githubusercontent.com/39856622/85922524-fe6bdc00-b8be-11ea-87d9-5e85e02689d9.png)

接触数の部分が押せることがわからないと書いてあったので、Adobe XDでお試しとして作ってみました。
直感的に接触数がわかるようにするため、接触数の部分を赤色にしてみました。どうでしょうか?

**Comment by T-taku** [comment]
![image](https://user-images.githubusercontent.com/39856622/85939483-e6449d00-b950-11ea-9007-fecd37e69d86.png)
もう一つ指摘されていた、
サブ要素が目立ちすぎているという指摘も修正してみました。
接触がなかったという部分の文字色を変更し、下線で見やすくしてみました。
これも、どの部分のコードを修正すればいいかわかりません...すみません。
どなたか修正できる方がいましたら、コメントで教えてください🙏

これまでの変更点のXDファイルをフォークしたリポジトリにpushしました:
 -->[T-taku/Covid19Radar/design/Community_COVID19Radar_Design.xd](https://github.com/T-taku/Covid19Radar/blob/423468753271381017a11b2ac10081a50a549ee5/design/Community_COVID19Radar_Design.xd)

**Comment by amay077** [comment]
> 追記:指摘されていた戻るボタンについては、XD上では、戻るボタンになっていたため、UIのミスかと思われます。

現状、「陽性者との接触確認」の画面をアプリで表示させることは容易ではなく、元のスクショがどのようにして得られたものか分からないので保留でよろしいかと思います。恐らく #648 が整理されるとこちらも自然と整理されると期待します。


> 接触がなかったという部分の文字色を変更し、下線で見やすくしてみました。

個人的な意見ですが、青字に下線はホームページのリンクである（タップできそう）と誤認されそうです（こういうデザインにしたらよいのではという提案ができなくてスミマセン）。

> どの部分のコードを修正すればいいかわかりません...すみません。

ある程度は https://qiita.com/Anharu/items/c00e882d678538be0ab0 が参考になります。
陽性者との接触は～ の画面は ``Covid19Radar/Covid19Radar/Views/HomePage/NotContactPage.xaml`` ですね。

**Comment by T-taku** [comment]
> 現状、「陽性者との接触確認」の画面をアプリで表示させることは容易ではなく、元のスクショがどのようにして得られたものか分からないので保留でよろしいかと思います。恐らく #648 が整理されるとこちらも自然と整理されると期待します。

なるほど...修正されることに期待するしかなさそうですね。

> 個人的な意見ですが、青字に下線はホームページのリンクである（タップできそう）と誤認されそうです（こういうデザインにしたらよいのではという提案ができなくてスミマセン）。

下線を消してみました。案外下線なしでも強調できている気がします。👍
![image](https://user-images.githubusercontent.com/39856622/85944551-8363fd80-b972-11ea-9c3c-0b91263c6029.png)

> ある程度は https://qiita.com/Anharu/items/c00e882d678538be0ab0 が参考になります。
陽性者との接触は～ の画面は Covid19Radar/Covid19Radar/Views/HomePage/NotContactPage.xaml ですね。

ありがとうございます!Qiitaの記事はみていませんでした😅

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
