### ISSUE TITLE
利用状況表示のUIが直感的でない

### ISSUE THREAD

**Issue by hiraly** [Covid-19Radar/Covid19Radar#534]
多くのユーザはこのアプリによって何かしらの形で「不安が解消されること」を望んでインストールすると想像しています。
また、利用者が増えることによってこのアプリの有効性（利用価値）が相関的に高くなることを考えると、「必要な許可権限をアプリに与えることで、アプリの目的が達成される」ことを伝えるフィードバックが足りないと感じています。

**改善案を画像にて示します。**

![ステータス情報差別化](https://user-images.githubusercontent.com/25720463/85215684-410d5000-b3b7-11ea-8396-28d29a425c96.png)

**この案で改善したいポイントを列挙します。**

- 端末パーミッションが取れている場合、緑で利用状態（アプリの目的が達成されていること）をユーザに直感的に伝える
- インストール後、真っ先に注目すべきポイントを他の（下部２つの）セクションと区別する

PS. 日本に暮らす人類の一人として、このアプリが広く利用されることを望んでいます。

**Comment by muak** [comment]
このUIにする場合、設定が無効な場合は
黄色エクスクラメーションに「〜〜が無効です」のような注意文を出す感じでしょうか？

**Comment by shogo82148** [comment]
利用状況の差別化には賛成です。

ただ、設定が無効な場合に黄色や赤のような警告色を使うのは、変に不安を煽ることになるのではと思いました。
無効になっているからと言って、すぐに危険な状況に置かれるわけではありません。

単に機能が無効になっていることを示せればよいので、グレーアウトではどうでしょう？

**Comment by hiraly** [comment]
> このUIにする場合、設定が無効な場合は
> 黄色エクスクラメーションに「〜〜が無効です」のような注意文を出す感じでしょうか？

このイメージでいましたが、しっくりこなかったのであえて書きませんでした。

> ただ、設定が無効な場合に黄色や赤のような警告色を使うのは、変に不安を煽ることになるのではと思いました。
> 無効になっているからと言って、すぐに危険な状況に置かれるわけではありません。
> 
> 単に機能が無効になっていることを示せればよいので、グレーアウトではどうでしょう？

なるほどです。しっくりこなかったのはここです。勝手にアイデアが集まるの最高ですねw

アプリをインストールしてあるのに機能を有効にしていないユーザには矛盾があります。
アプリへの不信感があるか、機能を正しく理解していないと思われるので、次のアクションを促す表示にしたいですね。

**Comment by hiraly** [comment]
「無効です。有効にするには〜」の文言に加えて、ホーム画面に https://github.com/Covid-19Radar/Covid19Radar/blob/master/img/explanation.png の画像をデデンと表示するのがお手軽でいいかなと思いました。

**Comment by muak** [comment]
こんな感じでしょうか？
アプリの設定のボタンを置いてみましたが、「使い方」へのボタンでも良さそうですね。
文言が難しいですね。


<img src="https://user-images.githubusercontent.com/16084475/85550628-1d1e6880-b65c-11ea-9c71-023b7e04a3bf.png" width="300" />&nbsp;<img src="https://user-images.githubusercontent.com/16084475/85550859-55be4200-b65c-11ea-907b-f6df485a7c20.png" width="300" />

**Comment by hiraly** [comment]
@muak 
いっすね！でもすみません、主張を変えます！

ちょっと要旨を見失ってました。
このアプリは **許可設定がされている** 状態によってのみ価値を発揮します。
「物を買う」「ノートをつける」といった能動的なアプリではないところが、モバイルアプリに多く触れたことのないユーザには伝わりづらい。というのがこのissueで一番解決したい点です。
ランニングアプリを起動して走り出したのにGPS許可がオフになってたら、デカデカと警告表示しますよね。それを直感的に伝えたい。

ですので、許可設定が無効となっているユーザには **積極的に許可設定を促す** ことが大事ですので、「！」マークで濃い黄色の警告色がよさそうです。

文言はよさげです。細かいですがもう少しすっきりさせて
「機能が無効になっています。設定ページで接触の検出と通知をONにしてください」くらいでよさそうです。

リンクは「アプリの設定へ」がいいですね！

「陽性者との接触を確認する」はもはやボタン非表示でいいような。
これって、設定が有効だった期間のみで判定できるんですかね？？そこの機能説明がどこにもないですね。詳しい人プリーズ

**Comment by muak** [comment]
@hiraly 
ありがとうございます。一度それで試してみます。

接触確認のボタンはどうなんでしょうね。
有効な期間で確認が可能だとしたら消すわけにはいかないと思いますし。

**Comment by muak** [comment]
組み込んでみました。どうでしょうかね？
チェックマークも!マークもMaterial Design Icons フォント内のものを利用しているので
特に追加のリソースは必要なく実装可能です。

<img src="https://user-images.githubusercontent.com/16084475/85650958-ad52c100-b6e1-11ea-97c3-5e239172a506.png" width="300" />&nbsp;<img src="https://user-images.githubusercontent.com/16084475/85650968-b17ede80-b6e1-11ea-8382-e5dd2cc4578a.png" width="300" />

**Comment by hiraly** [comment]
LGTM.

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも検討したいと思います。
