### ISSUE TITLE
submissionNumber is not long enough

### ISSUE THREAD

**Issue by tzik** [Covid-19Radar/Covid19Radar#535]
#514 からissueを分けます。

Diagnosis APIに渡される処理番号は数字8桁の文字列で、取りうる値は1億個しかありません。これは虚偽申告を防ぐのに十分な数ではないと考えます。
例えば、ある時点で有効な番号が1000個ほどあるとすると、10万回程度のランダムな試行で攻撃が成立する可能性が36%ほどあります。これは、悪意をもった攻撃者には達成可能な数であり、1000万人規模のユーザーのうち1%ほどが試みれば到達する数でもあります。

64bit程度に伸ばしてはどうでしょう。

**Comment by taku0** [comment]
64 bitの場合、数字だと20桁、Base 32だと13桁となります。
これはどの程度現実的でしょうか。
1つの考え方としては、操作が苦手な人は入院先で看護師の方にやってもらうというのもありますが、看護師の方の手間を増やしてしまいますし、陽性者の近くで操作する必要が出てしまいます。

**Comment by t-yamo** [comment]
当件について「虚偽報告を防ぐ必要があるか否か」という議論もあるかと思いますが、「発生の許容」「発生してからの対応」は運用レベルでの判断であり、システムとしては運用レベルでの判断に関わらず一定のセキュリティは確保しておくべきだと思いますので、システム的に何らかの方法で虚偽報告を防ぐという点について賛成です。

方向性としては
M1. 情報量の少ない処理番号に生存期間や物理的な制約を加える。
M2. 情報量を増やす。
が考えられるかと思います。

M1の一例としては、Bluetoothのペアリングや家庭用WiFiの設定のように発番システム側でポチった直後の短時間だけその処理番号での入力を許可するという方式などが考えられるかなと。
この方式だと時間的な制約で守られるため、処理番号の桁数が現在のように少ない形でも一定のセキュリティが確保できるかと思います。
ただし、処理番号の入力タイミングを制限する必要があるため、陽性の結果通知を対面でやるなど運用的な制約はそこそこ厳しいものになりそうな気はします。

M2の例としては、「処理番号の桁数を増やす」「電子署名を付ける」「（対面でやらなくてもよいレベルの情報量を持ち生存期間にちょっと余裕を持たせた）一時トークンを付ける」あたりがあるかなと。
この方式の場合は「処理番号をどのように通知するか」「処理番号をどのように入力してもらうか」が課題になるかと思います。
「処理番号の桁数を増やす」で64bitを超える情報量にする場合、[0-9a-zA-Z]のBase62でも11桁は要るのでなかなかの入力の手間ではありますね（ユーザ層を考えると大文字小文字混在は避けてBase36ぐらいにすべきか？）。
メールやSMSなどの電子的な通知を前提にできる場合は「QRコードを生成して読み取ってもらう」「インテントのパラメータに付ける」などの方式で手入力を回避できるかもしれません（新しい別の課題が出てくるかもしれませんが）。

**Comment by t-yamo** [comment]
#457 にも関連してくる部分かと思いますのでこのコメントでメンションしておきます。

**Comment by darkcrash** [comment]
今さら気づけましたが、、、リファレンスサーバーの仕様変わってますね。

８桁の仕様になってた経緯からいくと、元々のEN用のリファレンスサーバーが当初、任意の文字列だったところがあります。

https://github.com/google/exposure-notifications-server/blob/master/pkg/api/v1alpha1/exposure_types.go

プラットフォームごとに、DeviceCheckをかけるという仕組みだったのですが、それをやめたようですね。

**Comment by darkcrash** [comment]
ええ・・・とりあえずですが。

仕組みからいくと、リファレンスサーバーとクライアントENのAPIは直接つながっていないので、現状のままでも動作はすると考えられますが、リファレンスに追いかけるということであれば、それこそ大きな変更が発生することになりますと…。（ちょっと私個人が手に負えるようなことでもないですが）

それと、ここにあるAPIのサーバー群は、仕様書とリファレンスサーバーの実装に合わせてAzure Functionsで実装したものになります。

**Comment by t-yamo** [comment]
なるほど。
本題から逸れてしまう、かつ、既にドキュメント化されてたら申し訳ないのですが、「Covid19Radarにて議論できるスコープ」と「Covid19Radarが元にしている（もしくは参照先が変化していったとしてもここを基点に独自に実装していくよと決めた）仕様や参照実装のバージョン」ってどこかで定義されているものでしょうか。

issueに提案する際に「ここは直接的に変えられる」「ここは直接的には変えられないが外部と調整できる余地がある」「ここは変えられない」という部分の判断と、「参照実装と実装が違うのは、意図的に変えているものなのか、それとも本来追随しなければならない部分で漏れているのか」という部分の判断で悩むところではあります。

自分が当初処理番号まわりで考えていたのは一時トークンを付与する形であり、それは以下の2020/05/26版の「接触確認アプリ及び関連システム仕様書」の第1章 1.機能に関する事項 3) 認証の「認証情報」としての対応でした。
https://cio.go.jp/sites/default/files/uploads/documents/techteam_20200526_01.pdf

ただ、認証周りで変更が入ると工数的に厳しい部分もあるので、当issue( #535 )で出てきた桁数の変更ができるのであればその方向での対応もアリかなと思いました。

今回の話の流れからすると、基本的には新しめの参照実装を追いかけたい（当issueについてはJWTでの実現をめざしたい）が、工数や人員の制約なども鑑みて独自路線で行く場合もある、というのが現在の状況でしょうか。

**Comment by darkcrash** [comment]
そうですね・・・。
このリポジトリ自体は日本専用というわけでもないのでというのがあります。
それもあって明確にここまでという整理は現時点ではありません。
そのため最新の参照実装を追いかけることは一つの目標なのですが、今そこはちょっと置いといてですかね。

ご指摘の通り、認証情報としてのがCOCOAの仕様となるはずであるため、ここで変更したとしてもCOCOAに対しては、影響しないもしくは取り込まれたとしてもただ動かなくなるだけということです。
見ていただいている仕様の部分が必然と境界線になると考慮しないといけない部分ですね。

**Comment by taku0** [comment]
参考情報: ドイツの接触追跡アプリの場合、処理番号(teleTAN)は31種類の文字 × 10文字(内1文字はチェックサム)となっています。

ドイツの場合、通常は検査前にユニークなQRコードを読み込んでおき、検査結果はアプリを通じて通知され、そのままアップロードができるそうです。検査前にQRコードを読まない場合もサポートされていて、その場合はこのteleTANが発行されるとのことです。teleTANは1時間のみ有効とのことです。

https://github.com/corona-warn-app/cwa-documentation/issues/167
https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md

**Comment by shogo82148** [comment]
https://twitter.com/MHLWitter/status/1278666480402354178?s=20

> 接触確認アプリ（COCOA）により新型コロナウイルスの陽性者から通知を受けることができる機能を、７月３日から開始します。

このような発表がありましたが、この Issue は解消されたのでしょうか？

**Comment by kazumihirose** [comment]
当時およびリリース当初は、陽性登録管理システムとの接続をしていなかった為、このような形になってましたが、本件はHERSYSの8桁1時間OTP要件の話です。

また、こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
