### ISSUE TITLE
The start date changes daily

### ISSUE THREAD

**Issue by kashu-02** [Covid-19Radar/Covid19Radar#537]
**Describe the bug**
I have been using this app since June 19 but the start date of use changes daily.

**To Reproduce**

App installation date
1.Lanch the app.
The start day set for June 19.

Next day
1.Lanch the app.
The start day set for June 20.

…
Now, the start day set for June 21.

**Screenshots**
![A7C1A586-288B-4D4A-995C-B480B53BEDC5](https://user-images.githubusercontent.com/64694079/85218089-cf8ecb00-b3d1-11ea-8ef1-cfc7e28e84ad.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone11
 - OS: iOS13.5.1
 - App version : Ver 1.0.0
**Additional context**

**Comment by amay077** [comment]
duplicate #442 #491
