### ISSUE TITLE
About behavior when two buttons are pressed simultaneously.

### ISSUE THREAD

**Issue by akashima** [Covid-19Radar/Covid19Radar#538]
If you press two buttons at the same time and release them one by one, the action screen for each button is displayed and pushed to the navigation bar.

Steps to reproduce the behavior: (iOS)

See gif for details.

Screenshots:
![イメージ-2](https://user-images.githubusercontent.com/3690724/85218398-e8e54680-b3d4-11ea-8634-6237e29ec349.gif)

Device info:

Device: iPhone Xs
OS: iOS 13.5.1
Location: Tokyo, Japan
System region: Japan
Apple ID region: Japan
Version: 1.0.0

**Comment by akashima** [comment]
個人的な感覚ではあるのですが、片方のボタンアクションをキャンセルして良いと考えています。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでもマージいたしました。
