### ISSUE TITLE
Create App Center Automate UI Test

### ISSUE THREAD

**Issue by kazumihirose** [Covid-19Radar/Covid19Radar#54]
- We have to create an automated UI test. (Covid19Radar.UITest)
https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/

**Comment by mrbrl** [comment]
@kazumihirose my team can pick that one up!

**Comment by oyasan-ba2** [comment]
I'm start to think new test cases and test scenario.

**Comment by changeworld** [comment]
refs #295

**Comment by oyasan-ba2** [comment]
@changeworld I'd like to discuss not only test case but also test target.
I think UI may work with same behavior on any iOS and Android, but EN does not have same behavior.
This EN behavior may have different for each target.
@changeworld @kazumihirose What do you think this issue ?
