### ISSUE TITLE
connection error on submitting to accept the Terms of Use

### ISSUE THREAD

**Issue by anharu2394** [Covid-19Radar/Covid19Radar#543]
<img width="319" alt="スクリーンショット 2020-06-21 18 42 50" src="https://user-images.githubusercontent.com/26423094/85221487-2060ec80-b3ef-11ea-9754-38c68100e3ee.png">

I develop on Mac Book Pro.
I built and run Covid19Radar.Android and Covid19Radar.Functions with Visual Studio.
But, when submitting to accept the Terms of Use, cause connection error.

Do you have something else to make the app work successfully?
**Please tell me how to setup development environment and  make the app work successfully.**

PC: Mac Book Pro
Emulator: Pixel 3(Android 10)

**Comment by anharu2394** [comment]
related issue: #527

**Comment by chooyan-eng** [comment]
related issue: #539

**Comment by anharu2394** [comment]
現時点でローカルでapiと繋いで開発できる方法はありますか？ on mac book

**Comment by laiso** [comment]
自分が調べた結果を共有します(正式な方法ではないかもしれません)

Covid19Radar.Functions.sln をVisual Studio for Mac で開いて Covid19Radar.Api を実行すると`http://localhost:7071` でWeb APIにアクセスできると思います。

このアドレスを `Covid19Radar/Covid19Radar/settings.json` の`apiUrlBase` に設定するとアクセス先を指定することができます。

```json 
  "apiUrlBase": "http://localhost:7071/api",
```

この状態でiOSシミュレーター/Androidエミュレーターを使ってアプリ側の開発ができるかと思います。

同時に起動するにはVisual Studioアプリケーションのインスタンスを新規作成する必要があると思います。

https://docs.microsoft.com/en-us/visualstudio/mac/open-multiple-solutions?view=vsmac-2019

すべての箇所を確認したわけではないのでどこかで別のエラーが出たらすみません。

**Comment by anharu2394** [comment]
丁寧な回答ありがとうございます。
emulatorからの接続なので、

```
 "apiUrlBase": "http://localhost:7071/api",
```

では接続できず、

```
 "apiUrlBase": "http://10.0.2.2:7071/api",
```
にし、
試して見ました。


そうすると、利用規約ボタンを押すと、
`Cleartext HTTP traffic not permitted`というエラーが出たので、
AndroidManifest.xmlを
```
<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        android:networkSecurityConfig="@xml/network_security_config"
        ...>
        ...
    </application>
</manifest>
```
とすることでこのエラーはなくなりました。

しかし、そうすると、このような画面で固まります。
<img width="315" alt="スクリーンショット 2020-06-21 23 50 33" src="https://user-images.githubusercontent.com/26423094/85227718-17d1db80-b41a-11ea-8e2f-2ecc6094e04b.png">

また、このような例外をキャッチしました
<img width="499" alt="スクリーンショット 2020-06-21 23 51 24" src="https://user-images.githubusercontent.com/26423094/85227731-2ddf9c00-b41a-11ea-93df-5d2e1ebab2fd.png">

**Comment by anharu2394** [comment]
そして、api側ではこのような例外をキャッチしました
<img width="482" alt="スクリーンショット 2020-06-21 23 55 47" src="https://user-images.githubusercontent.com/26423094/85227843-c8d87600-b41a-11ea-80e9-fbf61179d348.png">

**Comment by chooyan-eng** [comment]
@laiso @anharu2394 

私も同じ状況で悩んでいたところ、お二方の投稿でここまで追いつくことができました。ありがとうございます。

私の環境でも同じ事象が発生しております。

少し調べたところ、エラーで出ている `accountEndpoint` は CosmosDB の接続先設定らしく、 API の方の `local.settings.json.example` ファイルに以下のように記述されています。

```
"COSMOS_CONNECTION": "AccountEndpoint=https://localhost:8081/;AccountKey=（以下略）",
```

おそらく、 CosmosDB に関しても Functions と同様にローカルで動作するよう環境構築が必要なのだと推測しています。

**Comment by anharu2394** [comment]
おそらく、CosmosDB emulatorというのをインストールして行えそうですが、macでインストールするのは邪道そうですね。やってみます。

**Comment by anharu2394** [comment]
いや、邪道というのは、結局、Windows仮想マシンにアクセスしてする方法なので、
macやlinuxで環境を構築というのはできなそうです
> Mac または Linux 上での実行
現在、Cosmos エミュレーターは Windows でのみ実行できます。 Mac または Linux を実行するユーザーは、Windows 仮想マシンによってホストされる、Parallels や VirtualBox などのハイパーバイザー内でエミュレーターを実行できます。 これを有効にする手順は、次のとおりです
https://docs.microsoft.com/ja-jp/azure/cosmos-db/local-emulator#running-on-mac-or-linux　  より

**Comment by chooyan-eng** [comment]
そのようですね。VM に Windows を入れるか、別の Windows PC で CosmosDB のエミュレーターだけ環境構築してローカルIPで接続するか、といったところになるかと思います。一旦後者の方法で試してみようと思っています。

**Comment by anharu2394** [comment]
## 現時点での結論
- Macでサーバーも立てて開発するには、CosmosDB emulatorが必要になりwindows仮想マシンを立てて行わなければならない
- Windowsではそれが可能
- #553 がマージされれば、サーバーを立てずにフロントエンド はおおよそ開発できるのでこの方法が最善なのではないか


とりあえず、#553 がマージされれば、このissueを閉じたいと思います。

**Comment by chooyan-eng** [comment]
なお、Azure Functions プロジェクトでは `local.settings.json` ファイルを `host.json` ファイルと同じ並びに置いておくそうなので、おそらくコミットされている `local.settings.json.example` ファイルをリネームすることで有効になりそうです。

https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-run-local?tabs=macos%2Ccsharp%2Cbash

このあたりも CosmosDB のエミュレーターが準備できたら試してみます。

**Comment by chooyan-eng** [comment]
> #553 がマージされれば、サーバーを立てずにフロントエンド はおおよそ開発できるのでこの方法が最善なのではないか

おお、もうプルリク出ていたのですね。これはその通りと思います。
この issue はバックエンドも含めて環境構築したい方の参考になるかと思います。

**Comment by chooyan-eng** [comment]
いろいろ試しまして、

- 別端末の Windows に CosmosDB をインストール & 起動
- `local.settings.json` の `COSMOS_ENDPOINT_URI` のホスト部分を、 Windows 端末のローカルIPアドレスに書き換え
- Mac に Windows への SSL 接続を許可するための設定（https://docs.microsoft.com/ja-jp/azure/cosmos-db/local-emulator#mac-os）
- `/Extensinos/IConfigurationExtension.cs` の `config["COSMOS_ENDPOINT_URI"]` などの値を `local.settings.json` の対応する値で書き換え

とすることでアプリのホーム画面まで遷移できました。

ただし、最後の `IConfigurationExtension.cs` の内容を書き換えたのは `local.settings.json` ファイルが読み込まれていなかった問題の苦肉の策のため、正しく読み込ませる方法は別途試してみます。ファイル名や置く場所が違うだけだと推測しています。

**Comment by anharu2394** [comment]
# 結論

#539 (アプリ通信のmock化)をして開発する。
