### ISSUE TITLE
android アプリの自動開始

### ISSUE THREAD

**Issue by nokemono** [Covid-19Radar/Covid19Radar#546]
アンドロイドを再起動したら機能がオフになってしまいました。
わりとよく再起動するので自動開始の機能がないと致命的になるかと思います。

**Comment by kenz** [comment]
機能がオフになったのはどのような方法で確認されましたでしょうか

**Comment by nokemono** [comment]
アプリを起動して
～から使用しています
という項目が、いつ見ても今日の日付になっています。
あと、ブルートゥースが自然と切れてしまいます。（これはアプリでどうにかできるのか不明ですが）

nexus5 
android 6.0.1

**Comment by unity709** [comment]
アプリの使用日数が起動する度に変わる現象は、
Galaxy S10 Android10でも確認できました。
Google Playストアのレビューのコメントを見ても、同じ現象の方が複数いるようです。

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and already fixed this issue.
