### ISSUE TITLE
Suggestion for NotContactPageButtonText

### ISSUE THREAD

**Issue by terrierscript** [Covid-19Radar/Covid19Radar#547]
**Is your feature request related to a problem? Please describe.**

* 接触確認画面における、「アプリを周りの人に知らせる」というボタンについての提案です。
* こちらのボタン、共有をするものかと思われますが、個人的な体験として、最初に見たとき単なる共有機能ではなく、なにか物理的な周囲に通知を飛ばすようなもののでは？と読めてしまいました。
* 自分なりに理由を考えてみましたが、おそらくアプリの性質上、「周り」というのが人間関係の周囲ではなく、物理的な周囲を表す箇所が多くなることが原因と考えます
* また、この文言はホーム画面の「本アプリを広めましょう」と同じ部分を利用しているものと思われますが、接触確認画面においては、この説明やソーシャルサービスのアイコンが無い事も原因かと思われます

**Describe the solution you'd like**

* 「このアプリを共有する」で十分妥当なのではないかと思われます。
* もう少し手を入れるのであればホーム画面の「本アプリを広めましょう」のタイトル・説明文・アイコンを含むブロックまでを接触確認画面にも表示すると意図が正しく伝わるのではないかと思われます。ただ、そのまま流用ですと少々見づらい可能性もあるかと思われます
  * [参考イメージ](https://user-images.githubusercontent.com/13282103/85222940-c31e6880-b3f9-11ea-9e17-7a5a739066b4.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも検討したいと思います。
