### ISSUE TITLE
Reduce app capacity with the Android App Bundle

### ISSUE THREAD

**Issue by takapi-Jr** [Covid-19Radar/Covid19Radar#548]
**Is your feature request related to a problem? Please describe.**
アプリ容量が大きいので減らしたい。
I want to reduce because the application capacity is large.

**Describe the solution you'd like**
apkからAndroid App Bundleに設定を変更することでアプリ容量を減らしたい。
I want to reduce the application capacity by changing the settings from apk to Android App Bundle.

**Describe alternatives you've considered**
1. AndroidプロジェクトのAndroidオプションからAndroidパッケージ形式を変更する。
Change the Android package format from the Android option in the Android project.
2. AndroidManifest.xmlに`android:installLocation="internalOnly"`を追加する。
Add `android:installLocation="internalOnly"` to AndroidManifest.xml.

**Additional context**
参考リンク(Reference link)
[Android App Bundle対応がリリースされたので試してみた](https://dev.classmethod.jp/articles/xamarin-android-app-bundle-getting-started/)

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでもマージいたしました。
