### ISSUE TITLE
Language Selection and Translation in the African Continent Area

### ISSUE THREAD

**Issue by kazumihirose** [Covid-19Radar/Covid19Radar#55]
Language Selection and Translation in the African Continent Area

**Comment by akshaycolombus** [comment]
can someone help without having any programming knowlegde?

**Comment by nonoxp** [comment]
> can someone help without having any programming knowlegde?

@akshaycolombus  yes, the translation process doesn't require programming skills, follow the instructions described here:
[HOW_TO_TRANSLATE_CONTRIBUTE](https://github.com/Covid-19Radar/Covid19Radar/blob/master/HOW_TO_TRANSLATE_CONTRIBUTE.md)
