### ISSUE TITLE
[iOS] Cut off label in side menu

### ISSUE THREAD

**Issue by 417-72KI** [Covid-19Radar/Covid19Radar#558]
**Describe the bug**
When open side menu, 3rd item `アプリに関するお問い合わせ` is cut off after `お`.

**To Reproduce**
1. Launch app
2. open side menu (click hamburger menu or swipe from left side)

**Expected behavior**
3rd item should show whole text `アプリに関するお問い合わせ`

**Screenshots**
![image](https://user-images.githubusercontent.com/4150060/85228386-23bf9c80-b41e-11ea-9f98-ea8249f1c961.png)

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS13.5
 - Browser: (safari)
 - Version: 1.0.0

**Additional context**
`UILabel` has `adjustsFontSizeToFitWidth` and `minimumScaleFactor` properties, which can adjust font size to display whole text.
(I'm sorry but I don't know Xamarin is supporting it.)

**Comment by CH3COOH** [comment]
本件、文字サイズを大きくしていると発生します。手順は以下の通りです。

1. [設定] -> [アクセシビリティ] ->  [画面表示とテキストサイズ] -> [さらに大きな文字]
2. フォントサイズを変更する

<img width="819" alt="スクリーンショット 2020-06-22 21 47 53" src="https://user-images.githubusercontent.com/137952/85289215-0815ce00-b4d2-11ea-976e-85db4d17c8f3.png">

**Comment by ShotaKashihara** [comment]
Android でも同様の現象を確認しました。

1. [設定] - [ユーザー補助] - [表示:フォントサイズ]
2. フォントサイズを[最大]に変更する

<img src="https://user-images.githubusercontent.com/26145133/85297372-a196ad00-b4dd-11ea-8836-24c535cd629a.png" height="500">
