### ISSUE TITLE
機微情報を暗号化ストレージに保管する

### ISSUE THREAD

**Issue by yamachu** [Covid-19Radar/Covid19Radar#566]
**Is your feature request related to a problem? Please describe.**

機微情報が暗号化されていない状態で保存されている。

現在の保管方法でもアプリケーションごとに分けられているストレージに保管されているため、他のアプリケーションからのアクセスが行うことは基本的には出来ない（superuser権限を持ってない限りは不可能（？））。
もしも行うことが出来た場合悪意のあるアプリケーションが情報（UserUuidやSecret）を読み取り、なりすましなどで申告などが行われるリスクがある。

**Describe the solution you'd like**

暗号化ストレージに機微情報を保存する。

**Describe alternatives you've considered**

保存する時に暗号化を施して現在の保管場所に保存する（Enc/DecのためのKeyはどうするかという問題がある）。

**Additional context**

**Comment by shogo82148** [comment]
把握はされていると思いますが、 #514 へのリファレンスを貼っておきます。
こちらでUserUuidやSecretを廃止する議論が進んでいます。

個人的には廃止の方向に進んでほしいと思っています。

**Comment by yamachu** [comment]
[PR](https://github.com/Covid-19Radar/Covid19Radar/pull/565 )の方には載せていましたが、Issueにはありませんでしたね。
refありがとございます。

**Comment by kazumihirose** [comment]
Secure Storageへの対応行いました。（本件は、事情がありまして、ハンドマージで行っています。）

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
Marge済みで、本コードでは対応していますが、実際に反映しているかは私のほうではわかりませんので、何卒ご了承ください。
