### ISSUE TITLE
StartDateTime is not working on Android

### ISSUE THREAD

**Issue by kenz** [Covid-19Radar/Covid19Radar#567]
**Describe the bug**
StartDateTime is not working on Android.
StartDateTimeはAndroid上で機能していない

**To Reproduce**
1.Enabled app
2.Launch the app in a few days.
3.Today's date is displayed in the StartDateTime on HomePage.

1.アプリを有効にする
2.数日後アプリを起動する
3.Homeの使用開始日はアプリ起動時の日付が表示される

**Smartphone (please complete the following information):**
 - Device: Pixel3
 - OS: Android 11 beta RPB1.200504.020

**Comment by changeworld** [comment]
refs #491
