### ISSUE TITLE
Unify Share links on Android and iOS

### ISSUE THREAD

**Issue by kenz** [Covid-19Radar/Covid19Radar#569]
**Is your feature request related to a problem? Please describe.**
The link is made to a platform-dependent store URL, so it cannot be shared with users on another platform.
アプリの共有において、リンク先がプラットフォームに依存したストアのURLとなっているため、異なるプラットフォーム向けのユーザーにアプリを共有できない。

**Describe the solution you'd like**
Link to https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/cocoa_00138.html
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/cocoa_00138.html のURLを共有する

**Comment by changeworld** [comment]
@kenz
ご提案ありがとうございます。
PRにも記載していますが、コミュニティの管轄外である「https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/cocoa_00138.html のURLを共有する」にするという内容ですと受け入れるのは難しいです。

- 「コミュニティとして管理している利用規約やプライバシーポリシーのように共有用のサイトを作成し、そこを共有する」
- 「共有用のサイトでは、レビューでリジェクトされないように、表示するプラットフォーム毎に表示を変える」

という内容なら可能かと思いますし、よい改善だと思いますので、確認してみます。

**Comment by kenz** [comment]
@changeworld 表示するプラットフォームごとに表示を変えると、当初の提案であるプラットフォームを越えた共有ができないと思います。
Androidの場合はそのような制限はないと思いますのでAndroidの場合はiOS,Androidのどちらのユーザーにとっても有益であるhttps://www.mhlw.go.jp/stf/seisakunitsuite/bunya/cocoa_00138.html へリンクしiOSの場合はリジェクトを避けるためAppStoreへリンクすると言う変更はいかがでしょうか？

**Comment by changeworld** [comment]
@kenz 
私の説明が悪くてすいません。
アプリをシェアした人の端末に依存せず、その共有されたサイトを見た人の端末毎にサイトで表示を変えるということです。

|-----|iOS端末|Android端末|
| ---- | ---- | ---- |
|iOSアプリから共有|AppStoreへのリンクのみ|PlayStoreaへのリンクのみ|
|Androidアプリから共有|AppStoreへのリンクのみ|PlayStoreaへのリンクのみ|

といった感じです。

**Comment by kenz** [comment]
@changeworld すいません、私の理解がずれていました。
その内容だと最高ですね。ユーザービリティは更に良くなりそう。

**Comment by TatsuyaYamamoto** [comment]
> 異なるプラットフォーム向けのユーザーにアプリを共有できない

kenzさんと同様に課題に感じ、本チケットを見つけました。

> 「コミュニティとして管理している利用規約やプライバシーポリシーのように共有用のサイトを作成し

共有用サイトが出来るまでの暫定策、または共有される側のダウンロードまでの操作の簡略化を狙って、共有文にiOS, Android両方のストアのURLを記載するというのはいかがでしょうか？
共有のための説明文も添えた方がより親切なものになると思います。

[AppUtils.cs](https://github.com/Covid-19Radar/Covid19Radar/blob/ce774f06c8/Covid19Radar/Covid19Radar/Common/AppUtils.cs)
```
        public static async void PopUpShare()
        {
            await Share.RequestAsync(new ShareTextRequest
            {
                Text = @$"{Resources.AppResources.AppName}

iOS: {AppSettings.Instance.AppStoreUrl}
Android: {AppSettings.Instance.GooglePlayUrl}"
            });
        }
```

<img width="339" alt="スクリーンショット 2020-07-03 12 09 43" src="https://user-images.githubusercontent.com/9045584/86427851-44dd9280-bd26-11ea-87b4-73443018a3d3.png">

**Comment by TatsuyaYamamoto** [comment]
立て続けにスイマセン、 @changeworld さんの [PR内の言及](https://github.com/Covid-19Radar/Covid19Radar/pull/570#issuecomment-647244188) (Appleのガイドラインで他platformへの言及は禁止されている) を確認しないまま↑の提案をしてしまいました。

「共有用サイトが出来るまでの暫定策」というのは変わらず、現行の仕様に対してAndroidアプリからの共有のみ以下の通りに変更する、に提案を変更させて頂きます。

----- | 共有文
-- | --
iOSアプリから共有 | AppStoreへのリンクのみを記載 (現行仕様)
Androidアプリから共有 | AppStore, PlayStoreへのリンクを記載 (変更点)

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
