### ISSUE TITLE
minSDKVersionが23のためRuntime Permission時の動作OSバージョンチェックは不要

### ISSUE THREAD

**Issue by LeoAndo** [Covid-19Radar/Covid19Radar#573]
minSDKVersionが23(Android M)のため、Runtime Permission時の動作OSバージョンチェックは不要のため削除できます

https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar.Android/Properties/AndroidManifest.xml#L3
https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar.Android/MainActivity.cs#L68

**Comment by kazumihirose** [comment]
Thank you for contribute, this is already marged.
