### ISSUE TITLE
Deselect ListView item when back to the help page

### ISSUE THREAD

**Issue by koogawa** [Covid-19Radar/Covid19Radar#574]
**Describe the bug**
I think the app should deselect an item in the help listview when the app navigated back to the help page. 

**To Reproduce**
1. Go to 'Help'
2. Click on some menu
3. Back to the help page

**Expected behavior**
Deselect ListView item when back to the help page.

**Screenshots**
![File](https://user-images.githubusercontent.com/893643/85252371-8eacba00-b496-11ea-9851-07e4d6366410.jpg)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 13.5

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.5

**Additional context**

**Comment by changeworld** [comment]
#468 で解決済ですので、クローズします。

**Comment by koogawa** [comment]
@changeworld https://github.com/Covid-19Radar/Covid19Radar/pull/468 の修正だけでは直っていないように見えました。
![image](https://user-images.githubusercontent.com/893643/85255545-712f1e80-b49d-11ea-88e8-acbfce00530b.png)

**Comment by changeworld** [comment]
@koogawa 
確かに直っていないですね。ラベル剥がしました。PRをマージしたらこちらもクローズされるので、オープンはしないでおきますね。
