### ISSUE TITLE
[iOS] In-App settings for notifications doesn't check notifications permission

### ISSUE THREAD

**Issue by gematsu** [Covid-19Radar/Covid19Radar#581]
**Describe the bug**
COVID-19 Contact App > App Settings > Notifications doesn't check whether the App has a permission to send notifications or not.

**To Reproduce**
1. App Settings
2. Notifications
3. The toggle turns on and it seems we can receive notifications from the App, but iOS's permission state isn't checked. If the iOS' permission settings turns off, we can't receive notifications from the App.

**Expected behavior**
Notifications settings should be synced or merged with iOS's Settings > COVID-19 Contact App > Notifications permission settings.

**Smartphone (please complete the following information):**
 - Device: iPhone SE (2020)
 - OS: iOS 13.5.1
 - Browser  stock browser
 - Version 1.0.0

**Additional context**
Related to this issue, there's no way to request the permission to send notifications once we select "Set up later" in "Turn on notifications" screen in the initial setup procedure. Thus we can't receive notifications unless we delete the whole app & data and reinstall it.

**Screenshots for additional context**
![ezgif-1-12ac807adc3a](https://user-images.githubusercontent.com/49086092/85264762-25d03c80-b4ac-11ea-83a7-a3e3e0185b64.gif)
![ezgif-1-fb42728713dc](https://user-images.githubusercontent.com/49086092/85264790-37194900-b4ac-11ea-94ac-41aa3a7ee25d.gif)

**Comment by gematsu** [comment]
日本語でも問題点をまとめます。
**Describe the bug**
接触確認アプリ > アプリの設定 > 通知 の設定項目がアプリに通知権限が付与されていることを確認しない。

**To Reproduce**
Steps to reproduce the behavior:
1. アプリを開き、左上のハンバーガーメニューから「アプリの設定」を開く
2. 「通知」のトグルを有効/無効を切り替える
3. OS側でアプリに通知権限が付与されていない状態であっても、アプリ上では通知が有効となってしまう

**Expected behavior**
OS側の権限設定と別にアプリ内へ通知有効/無効の設定項目を設けてしまうと、OS側の権限設定とアプリ側の設定の2箇所を同時に有効にしない限り通知機能が有効とならず、利用者にとって親切でない。
アプリ側に通知有効/無効の設定項目を設けずOS側の権限設定画面を呼び出してOS側で制御させる方式、もしくは有効へ切り替える度OS側で権限を許可されているか確認する方式への変更が望ましい（最近のアプリではiOS/Android問わず前者が主流となっている）。

**Smartphone (please complete the following information):**
Device: iPhone SE (2020)
OS: iOS 13.5.1
Browser: stock browser
Version: 1.0.0

**Additional context**
本問題に関連して、チュートリアル「通知をご利用いただくために」画面で「あとで設定する」を選択してしまうと、以降iOS側への通知権限リクエスト（権限確認）を一切行わないため、本アプリが通知機能を有するとiOS側で認識されず、OS側で権限を許可できなくなってしまう。 **この状況が発生した場合、アプリ内の通知設定を有効にしたとしても使用者は通知を一切受け取れず、また通知権限を付与することもできなくなってしまう（解決不能となる）。** 唯一、設定データを含め完全アンインストールを実行し、再インストール後チュートリアル画面をやり直し、該当画面で「有効にする」を選択することで解決できる。
（iOS側の 設定 > 一般 > iPhoneストレージ > 接触確認アプリ > Appを削除）
現実問題として、こちらの追記項目の方が問題としては致命的であるが、主題を解決すれば解決できるはずの問題のため追記項目とした。
なお、Androidではインストール時に自動で通知権限が付与されるため、追記項目の問題は発生しない。

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and maybe already fixed this issue.
