### ISSUE TITLE
MHLW logo is incorrect.

### ISSUE THREAD

**Issue by Grabacr07** [Covid-19Radar/Covid19Radar#583]
**Describe the bug**
MHLW logo image displayed in the navigation bar is incorrect (typo).

https://github.com/Covid-19Radar/Covid19Radar/blob/00e6aa6/Covid19Radar/Covid19Radar.Android/Resources/drawable-ja-xxxhdpi/HeaderLogo.png
https://github.com/Covid-19Radar/Covid19Radar/blob/00e6aa6/Covid19Radar/Covid19Radar.iOS/Resources/HeaderLogo%403x.png

![](https://user-images.githubusercontent.com/1779073/85266234-89f40000-b4ae-11ea-9696-a1acf24e055a.PNG)

**Expected behavior**
```
Ministry of Health, Labour and Welfare
                                     ^
```

For your reference, [homepage of MHLW](https://www.mhlw.go.jp/index.html):

![](https://www.mhlw.go.jp/content/000269499.png)

**Comment by changeworld** [comment]
@Grabacr07 
ご指摘ありがとうございます。
コミュニティに共有いただいた画像の問題だと思うので、共有してくれた方に正しい画像がないか聞いてみます。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ロゴにつきましては一時的な許諾を得て、利用しておりましたが、現在本リポジトリからの削除を進めております。
