### ISSUE TITLE
「アプリの使用中止」実施後は陽性情報が登録できなくなる

### ISSUE THREAD

**Issue by watanabetoshinori** [Covid-19Radar/Covid19Radar#584]
**Describe the bug**
「アプリの使用中止」を選択してアプリを再起動後、Diagnosis API(/api/diagnosis)を呼び出すとエラーになります。

**To Reproduce**
1. アプリ内の設定画面から「アプリの使用中止」を選択します
2. ダイアログの指示に従いアプリを再起動します
3. アプリを起動してチュートリアルを完了させます
3. 陽性情報の登録 > 同意して陽性登録するを選択します
4. パラメータ `userUuid` が存在しないためエラーとなります

**Expected behavior**

以下のいずれかの挙動が望ましいです。

- 「アプリの使用中止」実行後にも陽性情報を登録できること
- 「アプリの使用中止」実行後のメッセージにてアプリのアンインストールを促すこと

**Additional context**

不具合が発生するまでの関連処理は以下の通りです。

1. 「アプリの使用中止」を選択すると、UserDataに対して空データが上書きされます。

    [SettingsPageViewModel.cs#L67](https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs#L67)
    ```
    // Reset All Data and Optout
    UserDataModel userData = new UserDataModel();
    await userDataService.SetAsync(userData);
    ```

2. その後、ダイアログの指示に従いアプリを再起動すると、チュートリアルから開始されます。
チュートリアルではUserDataの存在有無をnullかどうかで判定しているため、空データの場合でも存在すると判定されてしまい Register User API(/api/register) が呼び出されません。APIが呼び出されないため `userUuid` が取得できずにnullのままになります。

    [UserDataService.cs#L24](https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar/Services/UserDataService.cs#L24)
    ```
    public bool IsExistUserData { get => current != null; }
    ```

3. この状態で陽性登録を実施すると、Diagnostic API(/api/diagnostic)のパラメータである`UserUuid`にnullが渡されます。

    [ExposureNotificationHandler.cs#L269](https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L269)
    ```
    UserUuid = userData.UserUuid,
    ```

4. Diagnostic APIではパラメータの検証が行われ、`userUuid`がnullの場合はエラーとなり登録を完了できません。

**Comment by Niccari** [comment]
以下PR分にて対応されました。
https://github.com/Covid-19Radar/Covid19Radar/pull/675
