### ISSUE TITLE
不要なNuGetパッケージを削除してアプリ容量を削減したい

### ISSUE THREAD

**Issue by takapi-Jr** [Covid-19Radar/Covid19Radar#588]
`Prism.DryIoc.Forms`は、`Prism.Core`と`Prism.Forms`を内包していたと記憶しています。
よって、下記は`Prism.DryIoc.Forms`のみで十分と思います。
* Prism.Autofac.Forms(iOSのみ選択されていたが、使用されてなさそう)
* Prism.Core
* Prism.DryIoc.Forms
* Prism.Forms

最近のXamarin.Formsのテンプレのプロジェクトを作成すると、`Xamarin.Forms`と`Xamarin.Essentials`しかありません。
よって、下記のNuGetパッケージに関しても、不要なのではと思いました。
* Xamarin.Android.Support.CustomTabs
* Xamarin.Android.Support.Design
* Xamarin.Android.Support.v4(MainApplication.csでusingされているが未使用)
* Xamarin.Android.Support.v7.AppCompat
* Xamarin.Android.Support.v7.CardView
* Xamarin.Android.Support.v7.MediaRouter

他にもあるかもしれませんが、私自身この辺りの知識があまりないので。。。

**Comment by rita0222** [comment]
手元で上記に記載のあるパッケージを削除してビルドし、
削除前後の apk サイズを比較しましたが、有意な差が認められませんでした。

| 削除前 | 削除後 |
|----|----|
| 35,519KB | 35,535KB |

Debug_Mock と Debug ビルドで確認しました。
不要なアセンブリはトリミングされているように見えます。
iOS 側は環境がないので不明です。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも容量削除については、検討したいと思います。
