### ISSUE TITLE
[使い方]で利用しているリソースが大きいような気がします。

### ISSUE THREAD

**Issue by einsoftlabjp** [Covid-19Radar/Covid19Radar#593]
[使い方]で利用しているビットマップなどのリソースが大きいような気がします。
アプリ容量を削減するためにWebへのリンクに変えてはいかがでしょうか

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも検討したいと思います。
