### ISSUE TITLE
The switch on the setting screen is shown in the center.

### ISSUE THREAD

**Issue by gaipoi** [Covid-19Radar/Covid19Radar#595]
- I think it is correct that it appears on the right side of the settings screen.

**Comment by hiroakit** [comment]
Thank you for writing issue.

In this screen, other contributor fight #608, #609 about other issue.

Please take love if you will may be conflicts.
Thank you.

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and already fixed this issue.
