### ISSUE TITLE
【Android/iOS】読み上げテキストの設定確認

### ISSUE THREAD

**Issue by TentaShion** [Covid-19Radar/Covid19Radar#596]
例えばTutorialPage1.xaml の"次へ" ボタンをAndroid で読み上げてみると"NextButton Button" となりました。
なのでこれを"次へ Button" となるように修正したいです。
また他にも同じような箇所がないかを調べていきたいです。

## 修正箇所一覧
ファイル名 | XD へのリンク | 修正箇所
--- | --- | ---
HelpPage/HelpMenuPage.xaml | [P3-1 Help] | ヘッダー戻る
HelpPage/HelpPage1.xaml | [P3-2 Exposure identification] | ヘッダー戻る
HelpPage/HelpPage2.xaml | [P3-2 Exposure confirmation] | ヘッダー戻る
HelpPage/HelpPage3.xaml | [P3-2 Positive confirmation] | ヘッダー戻る、「陽性情報の登録と他者への匿名通知へ」
HelpPage/HelpPage4.xaml | [P3-2 Record stop, Delete] | ヘッダー戻る、「アプリの設定へ」
HelpPage/InqueryPage.xaml | [お問い合わせ] | ヘッダーハンバーグ、メールアドレス、"9:00 ~ 17:30"、"土・日"
HomePage/ChatbotPage.xaml |  |  |
HomePage/ContactedNotifyPage.xaml |  |  |
HomePage/ExposuresPage.xaml |  |  |
HomePage/HomePage.xaml | [home default] | ヘッダーハンバーグ、ヘッダー使い方、「陽性者との接触を確認する」
HomePage/NotContactPage.xaml | [Exposure notifications-No contact] | ヘッダー戻る、「アプリを周りの人に知らせる」
HomePage/NotifyOtherPage.xaml | [Notify] | ヘッダー戻る、「登録する」
HomePage/PrivacyPolicyPage2.xaml | [プライバシーポリシー] | ヘッダーハンバーグ
HomePage/SubmitConsentPage.xaml | 陽性登録への同意 | ヘッダー戻る、「同意して陽性登録する」
HomePage/TermsofservicePage.xaml | [利用規約] | ヘッダーハンバーグ
HomePage/ThankYouNotifyOtherPage.xaml |  |  |
Settings/DebugPage.xaml |  |  |
Settings/LicenseAgreementPage.xaml | [ライセンス] | ヘッダー戻る、コンテンツ全般
Settings/SettingsPage.xaml | [アプリの設定] | ヘッダーハンバーグ
Tutorial/PrivacyPolicyPage.xaml | [P3-2 プライバシーポリシー] | 「同意する」
Tutorial/TutorialPage1.xaml | [P2-1] | 「次へ」
Tutorial/TutorialPage2.xaml | [P2-2 プライバシーについて] | 「利用規約へ」
Tutorial/TutorialPage3.xaml | [P3-2 利用規約] | 「規約に同意して次へ」
Tutorial/TutorialPage4.xaml | [P2-3 Bluetooth] | 「有効にする」「あとで設定する」
Tutorial/TutorialPage5.xaml | [P2-3 Notification] | 「有効にする」「あとで設定する」
Tutorial/TutorialPage6.xaml | [P2-3 Welcome] | 「ホーム画面へ」「使い方を学ぶ」
ExceptionPage.xaml |  |  |
MenuPage.xaml | [menu] | ヘッダー戻る

### 初回起動時
1. [P0 スプラッシュ]
2. [P2-1]
3. [P2-2 プライバシーについて]
4. [P3-2 利用規約]
5. [P3-2 プライバシーポリシー]
6. [P2-3 Bluetooth]
7. [P2-3 Notification]
→ Android は遷移スキップされているかも
8. [P2-3 Welcome]

### メインフロー
No | 0 |  | 1 |  | 2 |  | 3
:---: | :---: | :---: | :---: | :---: | :---: | :---: | :---:
1 | [home default]<br />↓<br />[home share] | →<br />左上ハンバーガー | [menu] | → | (No1 を参照) |  |  |
2 |  |  |  | → | [アプリの設定] | → | [ライセンス]
3 |  |  |  | → | [お問い合わせ] |  |  |
4 |  |  |  | → | [利用規約] |  |  |
5 |  |  |  | → | [プライバシーポリシー] |  |  |
6 |  | →<br />右上「使い方」 | [P3-1 Help] | → | [P3-2 Exposure identification] |  |  |
7 |  |  |  | → | [P3-2 Exposure confirmation] |  |  |
8 |  |  |  | → | [P3-2 Positive confirmation] | → | (No12 を参照)
9 |  |  |  | → | [P3-2 Record stop, Delete] | → | (No2 を参照)
10 |  | →<br />接触者なし | [Exposure notifications-No contact]<br />↓<br />[home share] |  |  |  |  |
11 |  | →<br />接触者あり | [Exposure notifications-Exposures-2 – 1] | → | [Exposure notifications-Exposures-List] |  |  |
12 |  | → | 陽性登録への同意 | → | [Notify]<br />↓<br />[Notify-Register] | → | [home registered]<br />↓<br />[home share]
13 |  |  |  |  |  | →<br />処理番号の取得方法 | (No8 を参照)

[Exposure notifications-Exposures-2 – 1]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/75a4be8c-98d7-4544-bd93-3c810c6b3963/Exposure-notifications-Exposures-2-1
[Exposure notifications-Exposures-List]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/6e6c8fe6-0cbc-4650-b499-d019495c1360/Exposure-notifications-Exposures-List
[Exposure notifications-No contact]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/46a72c2f-fc08-469f-bf82-5d86fc2ee5e0/Exposure-notifications-No-contact

[home default]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/8ed2d28f-8610-48e9-9b5d-e2b733999a92/HOME-Phase2-Default
[home registered]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/b4b97aa6-8421-4b44-a90d-0952beac1058/HOME-Phase2-Registered
[home share]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/9aaa9661-74fa-429f-8ef7-01b9a04d8d7b/HOME-Phase2-Share

[menu]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/4863e52f-ceaf-48ce-be47-360d0279dbe9/menu

[Notify]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/d7dca714-18e3-48f6-a429-1574017bf379/Notify
[Notify-Register]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/51e18571-b775-4bee-ad00-3a5fe4619b2d/Notify-Register

[P0 スプラッシュ]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/

[P2-1]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/584c1c19-9bf1-4d8d-bfe1-9d86f0e8196d/P2-1
[P2-2 プライバシーについて]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/5f7a1710-cb9f-4615-aa5c-c72581a1f1d5/P2-2-
[P2-3 Bluetooth]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/826ba3c2-3030-42a2-94c1-15485d931656/P2-3-Bluetooth
[P2-3 Notification]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/1103a579-fc71-45f5-b01a-afde393d22c3/P2-3-Notification
[P2-3 Welcome]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/05205c7a-d4e0-4ecc-b0ed-a4f6f4037dba/P2-3-Welcome

[P3-1 Help]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/5dd99626-25be-49c8-ad92-60db3e449d3b/P3-1-Help
[P3-2 Exposure confirmation]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/97bb3cec-ac5a-4d63-8338-f1834d6a3caa/P3-2-Exposure-confirmation
[P3-2 Exposure identification]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/4ebbb57a-23ac-44c0-b797-741aa175497b/P3-2-Exposure-identification
[P3-2 Positive confirmation]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/95431c88-0472-4bde-8eaa-0f02a0e619b0/P3-2-Positive-confirmation
[P3-2 Record stop, Delete]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/4aca9aac-f378-4380-a08d-40a6449d073f/P3-2-Record-stop-Delete
[P3-2 プライバシーポリシー]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/c616f92e-6f05-4f82-9f18-2013bb08207e/P3-2-
[P3-2 利用規約]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/642789a6-eee1-4edc-824a-7a929bc46660/P3-2-

[アプリの設定]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/97820e07-789f-4679-a983-ac5b23e8e1e6/-

[お問い合わせ]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/f9782daa-255e-45cf-aad9-b9bad74ae1c2/-

[プライバシーポリシー]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/479179c1-3a04-4b92-803d-0f4d1af79c35/-

[ライセンス]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/f7e0dcb0-6492-423c-ba0e-81eed8e11ef2/-

[利用規約]: https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/3f4fac1e-d08b-4583-b313-54d8bae77df8/-

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでもマージいたしました。
