### ISSUE TITLE
Implement NotificationCreate Api

### ISSUE THREAD

**Issue by darkcrash** [Covid-19Radar/Covid19Radar#61]
Create NotificationCreate Api, NotificationCreateParameter and NotificationCreateResult.

Requirements
- [ ] Route "Notification/Create"
- [ ] HttpMethod "POST"
- [ ] authLevel Function.
- [ ] Include NotificationCreateParameter has Title, Message.
- [ ] Include NotificationCreateResult has nothing ... I'll think about it later.

**Comment by csleead** [comment]
Could you please explain more about this API? What this API is supposed to do?

**Comment by darkcrash** [comment]
@csleead 
This API writes to the CosmosDB Notification collection.
This function allows user to register any message from outside the application.
