### ISSUE TITLE
Reduce image file size

### ISSUE THREAD

**Issue by seventhmoon** [Covid-19Radar/Covid19Radar#610]
**Is your feature request related to a problem? Please describe.**
The app size is too big, optimization can be done by lowering the color depth, and using WebP format for image used in Android

**Describe the solution you'd like**
1. Convert image to WebP or VectorDrawable
2. Reduce color depth of the image.
It could save up to 90% of the file size of the image.

**Additional context**
https://squoosh.app/editor is a tools for you to preview the changes

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal, this is merged.
