### ISSUE TITLE
[Android]スプラッシュスクリーン後にクラッシュする

### ISSUE THREAD

**Issue by takapi-Jr** [Covid-19Radar/Covid19Radar#612]
現時点でのmaster最新、Debug版でビルドして実行しました。
下記エラーメッセージが表示され、その後クラッシュしました。
```
Java.Lang.RuntimeException: 'Unable to get provider androidx.work.impl.WorkManagerInitializer: java.lang.ClassNotFoundException: Didn't find class "androidx.work.impl.WorkManagerInitializer" on path: DexPathList[[zip file "/data/app/jp.go.mhlw.covid19radar-1/base.apk"],nativeLibraryDirectories=[/data/app/jp.go.mhlw.covid19radar-1/lib/x86, /data/app/jp.go.mhlw.covid19radar-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]'
```

* Device: Zenfone 2
* OS: Android 6.0.1

**Comment by takapi-Jr** [comment]
Debug_Mock版ではクラッシュは起きませんでした。

**Comment by takapi-Jr** [comment]
Debug版
[Androidプロジェクトの右クリックメニュー]-[プロパティ]-[Androidオプション]-[Multi-Dexを有効にする]をoffにすると正しく動作しました。

**Comment by takapi-Jr** [comment]
Release版
[Androidプロジェクトの右クリックメニュー]-[プロパティ]-[Androidオプション]-[リンク中]をなしに設定した場合のみ動作しました。
しかし、この設定にすると、アプリ容量が増えます。
* apkの場合、140MB程度
* aabの場合、120MB程度

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。

なお、本クラッシュ(Exception)はExposure NotificationへのAPIアクセスが制限されている事から発生するものです。
