### ISSUE TITLE
[iOS14 beta] アプリが起動しない

### ISSUE THREAD

**Issue by nishimao** [Covid-19Radar/Covid19Radar#615]
**Describe the bug**
iOS14 betaにてホームアイコンをタップするとアプリが起動スクリーン表示後にクラッシュします。
β版OSなので優先度は低で問題ないと思います

コンソールのログは以下のようになっています

com.apple.UserNotifications	RemoteNotifications	デフォルト	14:39:01.529712+0900	UserNotificationsServer	SpringBoard	[jp.go.mhlw.covid19radar] jp.go.mhlw.covid19radar application state changed to ForegroundRunning
		エラー	14:39:01.536515+0900	Sandbox	kernel	Sandbox: Covid19Radar.iOS(1805) deny(2) file-test-existence /usr/bin/gdb
		エラー	14:39:01.536546+0900	Sandbox	kernel	Sandbox: Covid19Radar.iOS(1805) deny(2) file-test-existence /bin/gdb
		エラー	14:39:01.536581+0900	Sandbox	kernel	Sandbox: Covid19Radar.iOS(1805) deny(2) file-test-existence /sbin/gdb
		エラー	14:39:01.536607+0900	Sandbox	kernel	Sandbox: Covid19Radar.iOS(1805) deny(2) file-test-existence /usr/bin/lldb
		エラー	14:39:01.536628+0900	Sandbox	kernel	Sandbox: Covid19Radar.iOS(1805) deny(2) file-test-existence /bin/lldb
		エラー	14:39:01.536647+0900	Sandbox	kernel	Sandbox: Covid19Radar.iOS(1805) deny(2) file-test-existence /sbin/lldb

**再現手順**
1. ホーム画面を表示する
2. 接触確認アプリのアイコンをタップ
3. 起動スクリーンが表示された後、クラッシュ発生

**期待する動作**
アプリが起動する

**Smartphone (please complete the following information):**
 - Device: [iPhone11 pro]
 - OS: [iOS14.0]

**Additional context**
beta版OSのため対応優先度は低だと思います

**Comment by akira-sasaki** [comment]
[https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-14-beta-release-notes)

iOS 14 Betaでは、ExposureNotification APIは、まだ非対応みたいですね。

**Comment by shinriyo** [comment]
未対応のときはクラッシュではなく、ダイアログか何か出しますかね？

**Comment by kazumihirose** [comment]
当時、BetaではEN実装が含まれていなかったために起こっていた事象です。
ご報告いただきありがとうございました。
