### ISSUE TITLE
Cannot access App Center

### ISSUE THREAD

**Issue by csleead** [Covid-19Radar/Covid19Radar#62]
When I tried to access [App Center](https://install.appcenter.ms/orgs/Covid19Radar/apps/Covid19RadarAndroid/releases), It said **Your account doesn't have access or this app doesn't exist**.
Perhaps the permission setting is not correct?

**Comment by changeworld** [comment]
Me too.

**Comment by shunsuke-kawai** [comment]
I think we have to get the App Center admin to register as a tester for download it.
Maybe because of the iOS distribution terms.

**Comment by changeworld** [comment]
I was informed that we were limiting the users who could access the App Center.
