### ISSUE TITLE
iOS HotReload 対応

### ISSUE THREAD

**Issue by muak** [Covid-19Radar/Covid19Radar#623]
Visual Studio で iOS のビルド設定が「SDKのみをリンクする」となっており
この状態だとシミュレータのHotReloadが効かないため
Xamlの修正が即時画面に反映されず、再ビルドする必要があります。

HotReloadを効かせるため、Debug_Mock 構成の設定では「リンクしない」に設定した方が画面修正がしやすいと思います。

Android版は現状でHotReloadは効いています。

**Comment by amay077** [comment]
FYI として。

[Covid19Radar/Developer-Node.md at master · Covid-19Radar/Covid19Radar](https://github.com/Covid-19Radar/Covid19Radar/blob/master/doc/Developer-Node.md#exposure-notification) 
には、Exposure Notification 使用のために「Link Framework SDK's Only」が必要と書かれていますが、Debug_Mock 構成では、[Exposure Notification API も Mock 化](https://github.com/Covid-19Radar/Covid19Radar/issues/495#issuecomment-646970311)しているため Don't Link でも問題なさそうです。

が、Debug_Mock 以外の構成を変更することには注意が必要です。

**Comment by muak** [comment]
こちらは、HotReload利用時だけ都度「リンクしない」に設定して対応するとのことなのでCloseします。
