### ISSUE TITLE
アプリ設定ページ、画面下側に部品がない場所までスクロールが可能

### ISSUE THREAD

**Issue by takapi-Jr** [Covid-19Radar/Covid19Radar#625]
アプリ設定ページの画面下側、何も配置してない箇所までスクロールが可能。
スクロールの制限をしたい。
![Screenshot_20200623-213031](https://user-images.githubusercontent.com/25080529/85404157-84271900-b599-11ea-93da-77270c65505a.png)

**Comment by syobonpastel** [comment]
![image](https://user-images.githubusercontent.com/58867517/85827662-ad29f280-b7c1-11ea-847d-8cd0fbbed32c.png)
ios版でも同様でした。
アプリの設定とプライバシーポリシーのところが、スクロールできてしまっています。

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
and maybe already fixed this issue.
