### ISSUE TITLE
陽性情報の登録ページ、Entryの入力文字サイズが小さい

### ISSUE THREAD

**Issue by takapi-Jr** [Covid-19Radar/Covid19Radar#629]
StyleにはDefaultEntryが指定してあり、文字サイズはSmallでした。
なお、他にEntryの実装箇所はないので、DefaultEntryの使用もこちらのみです。

![Screenshot_20200623-212504](https://user-images.githubusercontent.com/25080529/85410164-b5a3e280-b5a1-11ea-917f-a03c8763fb19.jpg)

**Comment by hiroakit** [comment]
Thank you for your note.

What are the benefits of responding?
Could you write your opinion about it?

**Comment by takapi-Jr** [comment]
利用者が番号を入力するという話を聞いたので、文字サイズが小さいと困る方もいるのでは、と思いました。

**Comment by hiroakit** [comment]
I copy.
You have a amazing mind. Great!

Thus, would you write your opinion on top comment.

**Comment by takapi-Jr** [comment]
下記環境で比較してみました。
* Device: Zenfone 2
* OS: Android 6.0.1

iOSへの影響が気になりますが、Placeholderとの間隔を考慮に入れると、文字サイズDefaultが妥当ではないかと思いました。

![比較](https://user-images.githubusercontent.com/25080529/85647574-ba6bb200-b6d9-11ea-99a5-41f285abfee5.png)
