### ISSUE TITLE
Cannot erase phone number in the Status Settings

### ISSUE THREAD

**Issue by fujie** [Covid-19Radar/Covid19Radar#63]
Cannot erase/modify mobile phone number in the Status Settings page. Del/back key does not work if users want to change phone number while setting up.

Environment:
- App version : Version 1.0 (196)
- Operating system : Android 10
- Phone model : Google Pixel 4

**Comment by changeworld** [comment]
ご指摘ありがとうございました。
最新のUIでは、電話番号を入れることがなくなったため、この Issue は閉じさせていただきます。
