### ISSUE TITLE
Support mail text is always Japanese - I'd propose to add "(Japanese only)" etc. next to the appsupport@ link in the 'Support' page

### ISSUE THREAD

**Issue by ykrtk** [Covid-19Radar/Covid19Radar#630]
**Describe the bug**
When clicking 'appsupport@cov19.mhlw.go.jp' link in the Support page, the email text is always Japanese, no matter what language is selected for iOS or the app.
Though I understand that this app is for Japanese and MHLW probably doesn't have any resources for handling emails written in other languages, it'd be better to add some notification that only Japanese email will be accepted.

**To Reproduce**
1. Your iOS's language is any language other than Japanese (I tested English), or from the iOS setting, change the language of the COCOA app to any language other than Japanese (I tested English and Simplified Chinese)
1. Go to 'Support' from the app menu
2. Click on 'appsupport@cov19.mhlw.go.jp' link
3. The mail subject and body are always Japanese. Those who don't speak Japanese may find it difficult to send report/feedback

**Expected behavior**
(If MHLW can handle non-Japanese mails) : localize the mail text based on the app's language
(If MHLW can't handle non-Japanese mails) : add some short text, such as "(Japanese only)" next to the link

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 13.5.1
 - Browser Safari
 - Version: App version 1.0.0

**Comment by shogo82148** [comment]
That's good idea, but we should avoid using the sentence "(Japanese only)".
ref. https://github.com/Covid-19Radar/Covid19Radar/pull/481

My suggestion is "Please write in Japanese".

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
