### ISSUE TITLE
(minor) the app doesn't show Wareki date

### ISSUE THREAD

**Issue by ykrtk** [Covid-19Radar/Covid19Radar#631]
**Describe the bug**
The app shows 2020年 even when 和暦 is used on the phone

**To Reproduce**
1. Go to iPhone settings -> General
2. Language and Regions
3. Set calendar to 和暦
4. Restart the app
5. On the top page, 2020年 6月 X日 is shown

**Expected behavior**
令和2年 6月 X日

**Screenshots**
![covid_t](https://user-images.githubusercontent.com/67327717/85418982-79c24a80-b5ac-11ea-82fe-9a76f8f7c5af.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.5.1
 - Version: App version 1.0.0

**Additional context**
Minor issue

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
