### ISSUE TITLE
It Takes a little while for HomePage to appear

### ISSUE THREAD

**Issue by anharu2394** [Covid-19Radar/Covid19Radar#636]
**Describe the bug**
It Takes a little while for HomePage to appear.
Why is HomePage slow to appear?
if HomePage is slow to appear, the app should display a splash screen while HomePage is loading.

**To Reproduce**
1. Run the app

**Smartphone (please complete the following information):**
 - Device: Huawei mate 10pro
 - OS: android9

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.
