### ISSUE TITLE
[Android]Backキーによる画面遷移の改善

### ISSUE THREAD

**Issue by amay077** [Covid-19Radar/Covid19Radar#648]
**Is your feature request related to a problem? Please describe.**

現在の Android 版アプリでは、Back キーによる画面遷移は次のように動作しています。

1. アプリ起動
2. ホーム 画面が表示される
3. ナビゲーションドロワー(左サイドメニュー)から アプリの設定 を押下
4. アプリの設定 画面が表示される
5. Back キーを押下
6. アプリが終了する

しかし、Back キーですぐにアプリが終了することは「あれ？アプリ終わっちゃった」と、少々違和感があります。

例えば、Twitter の Android アプリでは、

- 起動 → HOME → 検索 → BACK → HOME → BACK → 終了
- 起動 → HOME → 検索 → 通知 → BACK → HOME → BACK → 終了

というように、必ず HOME 画面を経由して終了するようになっています。
こちらの画面遷移の方が自然に感じます（他にも GMail、メルカリなど多くのアプリは Twitter と同じ挙動になっています）。

**Describe the solution you'd like**

Back キーでは、必ず ホーム 画面を経由してからアプリ終了となるようにします。

**Describe alternatives you've considered**

いくつかのアプリでは、Back キーを２回続けて押す（一度押すと「もう一度 Back を押すとアプリが終了します」という Toast が表示される）タイプもありますが、HOME を経由するほうが自然に感じます。

**Comment by amay077** [comment]
いくつか調査したことを共有しておきます。どなたかの役に立てば幸いです。

### 案1： NavigationPage のネスト

[Xamarin.FormsでのMasterDetailとバックボタン - Qiita](https://qiita.com/yu_ka1984/items/95c24aaae7d58c8b9a4b) の方法

- 理想に近いが、NavigationPage を入れ子にすることで予期せぬ挙動を呼び込む可能性も
- 本アプリは Prism に画面遷移を任せているので適用できないかも
- そのため情報だけ仕入れて未検証

### 案2： Prism の DeepLink Navigation

[Navigation Basics | Prism](https://prismlibrary.com/docs/xamarin-forms/navigation/navigation-basics.html) の方法

``MenuPageViewModel`` にて、

``NavigationService.NavigateAsync("NavigationPage/SettingsPage")`` としているところを、
``NavigationService.NavigateAsync("NavigationPage/HomePage/SettingsPage")`` とする。

これで期待する アプリの設定 → BACK → ホーム が実現できたが、アプリの設定 が ホーム の小画面という関係になってしまって意図しない結果に。具体的には、アプリの設定 でナビゲーションドロワー(ハンバーガーメニュー)が表示されなくなってしまった。

### 案3： SettingsPage/SettingsPageViewModel で画面終了のイベントを補足してホームへ遷移する

ベタだけど確実な方法かな、と思ったが今のところ期待した結果が得られず。

- SettingsPageViewModel の ``OnNavigatedXXX / Destroy`` は BACK キー押下時に呼び出されず。
- SettingsPage の OnDisappearing で base を呼ばすに HomePage へ遷移しても、なぜかアプリが終了してしまう

### 案4： Android Side で仕掛けを作る

[Handle Back Button in Xamarin Forms for Android - Bohdan Benetskyi - Medium](https://medium.com/@benetskyybogdan/handle-back-button-in-xamarin-forms-for-android-7e1557ce6e59) の方法。

未検証。

- MainActivity.cs で OnBackPressed を override する方法。
- Xamarin.Forms 側との通信に小細工が必要
- iOS アプリへの影響は小さくできそう
- Android アプリでは、全ての画面に影響する（OnBackPressed のフックが意図しない結果を生むかもしれない。例：モーダルダイアログを閉じる目的で BACK を押したらどうなる？）

**Comment by takapi-Jr** [comment]
個人的には案2が実装コストが低く、HOMEを経由した終了ができるので良いと思いました。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでもマージいたしました。
