### ISSUE TITLE
厚生労働省のシンボルマークの使用についての記載が欲しい

### ISSUE THREAD

**Issue by daisukekoba** [Covid-19Radar/Covid19Radar#653]
**Is your feature request related to a problem? Please describe.**

920fd448, 886cae10, e4266f49 で厚生労働省のシンボルマークを含む画像を追加していますが、厚生労働省のシンボルマークには使用条件があります。
https://www.mhlw.go.jp/kouseiroudoushou/symbol/shiyou.html
上記の条件により Covid19Radar を Fork した場合、厚生労働省のシンボルマークを使用できないと思います。

**Describe the solution you'd like**

README に厚生労働省のシンボルマークの使用について書いておく必要があると思います。

**Describe alternatives you've considered**

**Additional context**

ところで、このプロジェクトはどの条件により厚生労働省のシンボルマークを使用しているのでしょうか？
関連: #583

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
また、厚生労働省ロゴにつきましては、一時許諾を得ての結果でしたが、現在は削除を行う予定となっております。
