### ISSUE TITLE
プロジェクトにおけるテーマの設定と、それに基づいたissueの整理を行いたい

### ISSUE THREAD

**Issue by rita0222** [Covid-19Radar/Covid19Radar#654]
# Summary
* やることのテーマを何軸か立てて、それに基づいてissueを整理したい
* テーマに基づいて整理しておくことで、後からテーマ単位で優先度を調整でき、取り組むべき課題が明確になりやすい

**Is your feature request related to a problem? Please describe.**

現状、プロダクトとしてのマイルストーンが明文化されておらず、動きづらさを感じています。
最終的に何をどう反映していくのかが不透明なので、細かく当たり障りのない（と思われる）部分にしか手を出せない状況です。

**Describe the solution you'd like**

そこで、取り組むべきテーマを何軸か立て、それに基づいてissueを整理することを提案します。
これには次のような効果が期待できます。

* プロダクトが目指すべき方向性がわかりやすくなる
* テーマという大き目の粒度で課題を俯瞰することにより、優先度を考えやすくなる
* テーマごとに「今動かせる課題か否か」という判断がしやすくなる
* 優先度が変化した際には、そのテーマをまるごと「優先して取り組むべき課題」として扱うことができる

**Describe alternatives you've considered**

ベストなのは、優先度を透明性のあるプロセスで迅速に決定できることだと思われます。
しかし、プロダクトの置かれている状況が複雑であり、それが困難であることも承知しています。

現状の「細かく当たり障りのない（と思われる）部分」を各自で判断してコミットすることが、
オープンコミュニティにおいて今できる最善手である、という意見もあるかと思います。

**Additional context**

# Draft of themes

「動かしやすさ」の初期値は筆者の主観により決めています。

## 開発作業の効率化
* 動かしやすさ：高
* examples:
  - 開発ドキュメントの整備
  - CIの整備
  - リファクタリング

## ユーザビリティ向上
* 動かしやすさ：高
* examples:
  - 文字列表示の調整
  - 読み上げテキストのフォロー
  - 機能追加を伴わないUIの改善
  - アプリのサイズ削減

## ユーザが被る不利益の低減
* 動かしやすさ：中～高
* ≒BugFix
* examples:
  - クラッシュの回避
  - バッテリーや通信量の過剰消費低減

## 個人情報管理ポリシー見直し
* 動かしやすさ：低(難しい?)
* example:
  - userUuid, secretに関するissue

## 追加すべき機能の検討
* 動かしやすさ：低(プロダクトオーナーの意志決定が必要?)
* ≒Feature Plan(?)
* examples:
  - ユーザーにとって有用な情報提示

# Operations

* 各テーマごとにラベルを作り、issueに割り当てる
  - 複数のテーマに該当するissueがあってもいい
    - 可能ならばissueを分割する
  - できればテーマラベルは自由に貼り付けられる方がいい
* 各テーマが持つ「動かしやすさ」と「優先度」を定期的に更新し、分かりやすい場所に掲示する
  - コアコントリビュータが担う必要あり

# Conclusion

本リポジトリの運用方針が今後どのようになるのか、まだわからないことも多いです。
しかし、方針の交通整理を行うことで、これまでのコントリビューションを無駄にせず、
状況の推移次第では最終的なプロダクトにコミットできる人を増やすことにつなげられると考えます。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
また、ご提案いただいたIssueは個人的に非常に有意義なものと感じます。是非、COCOAのリポジトリにてご提案いただければと思います。
