### ISSUE TITLE
メニュー画面、選択したセルの色が戻らない

### ISSUE THREAD

**Issue by takapi-Jr** [Covid-19Radar/Covid19Radar#660]
**Describe the bug**
メニュー画面から任意のページを選択して、再度メニュー画面を表示すると、選択したセルが青く表示される。

**To Reproduce**
1. メニュー画面を表示
2. 任意のページをタップして、画面遷移
3. 再度メニュー画面を表示
4. 2.で選択したセルが青く表示されたまま

**Expected behavior**
画面遷移後にメニュー画面を開いたとき、選択したボタンに選択色が付いていないこと。

**Screenshots**
![Screenshot_20200625-155756](https://user-images.githubusercontent.com/25080529/85672224-9e7a0780-b6fd-11ea-9fd0-b9e90ffb40bf.jpg)

**Smartphone (please complete the following information):**
 - Device: Zenfone2
 - OS: Android 6.0.1

**Additional context**
類似の問題 #574

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでマージさせていただきました。
