### ISSUE TITLE
[Android] ユーザ補助オプション「アニメーションの削除」が反映されない

### ISSUE THREAD

**Issue by pinterior** [Covid-19Radar/Covid19Radar#674]
**Describe the bug**

ユーザー補助オプション「アニメーションの削除」を有効にしていたとしても、一部の画面遷移がアニメーションと共に行われる。

**To Reproduce**

1. 「設定」アプリの「ユーザー補助」から「アニメーションの削除」を有効にする
2. このアプリを起動する
3. 中央の「陽性情報の登録」あるいは右上の「使い方」をタップする
4. アニメーションと共に画面が遷移する

**Expected behavior**

アニメーションなしに画面が遷移する。

**Smartphone (please complete the following information):**

 - Device: SH-M08
 - OS: Android 9 (ビルド番号02.00.08)

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
