### ISSUE TITLE
Additional zh-Hant translation

### ISSUE THREAD

**Issue by amouro** [Covid-19Radar/Covid19Radar#676]
There are more translation needs review in zh-Hant.

**Comment by amouro** [comment]
やります

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでもマージさせていただきました。
