### ISSUE TITLE
[ios版]使い方でのスクショと実際の画面に差がある

### ISSUE THREAD

**Issue by syobonpastel** [Covid-19Radar/Covid19Radar#678]
![image](https://user-images.githubusercontent.com/58867517/85828262-ef9fff00-b7c2-11ea-9066-fd1ce89db9e0.png)![image](https://user-images.githubusercontent.com/58867517/85828268-f29aef80-b7c2-11ea-8ae8-88712ae998be.png)

使い方の画面では、使用開始後の日数が表示されているものなっていますが、実際には表示されていません。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
