### ISSUE TITLE
[Android]No confirm on  term of use and privacy policy, and show incosistence “使用中“text.

### ISSUE THREAD

**Issue by it00h** [Covid-19Radar/Covid19Radar#679]
**Describe the bug**
1.Applicatin start without confirmming term of use and privacy policy
2. Show “使用中“text  while not enabled contact tracing.

**To Reproduce**
1. Download app.
2. Open os‘s 設定
3. tap Google
4. Tap covid19(新型コロナウイルス感染症)の濃厚接触の可能性の通知
5. tap “開く“ on 新型コロナ接触確認アプリ　| 開く
6.  Splash screen shown. 
7. next dialog  ask “COVID-19(新型コロナウイルス感染症)の濃厚接触の可能性の通知をオンにしますか。“
8. Tap “キャンセル“
9. Main screen shown with “2020年6月xx日から使用中“

**Expected behavior**
1.on Step7 app. must confirm terms of use and privacy policy.
2. On step9, show “使用中“is inconsistent with users selection “キャンセル “.  Main screen must not show before user agreement confirmed.

**Smartphone (please complete the following information):**
 - Device: android shv40
 - OS: 9
 - Version : 1.0

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
