### ISSUE TITLE
The tag name of the UUID of the detected beacon is incorrect.

### ISSUE THREAD

**Issue by takapi-Jr** [Covid-19Radar/Covid19Radar#68]
検出済ビーコンのUUIDのタグ名が間違っています。
スクリーンショット画像の中では[VZ7Hf][ID!!]と表記されています。

**Overview**
The tag name of the UUID of the detected beacon is incorrect.
In the screenshot image, it is written as [VZ7Hf] [ID !!].
**Test terminal**
Zenfone 2(Android 6.0.1)
Zenfone 4(Android 8.0.0)
**Build number**
197

![Screenshot_20200425-174204](https://user-images.githubusercontent.com/25080529/80275613-69f9c780-871d-11ea-961b-75d4fa97a068.jpg)

**Comment by yoichinak** [comment]
Resolved by:
- 95b7c0ea4dd8066d0817b198f6283ddcd4fe3f5c Covid19Radar.ja.xlf Line 242
- 53554c81c5004354ac9e3ff2e3fb08ab10a997fa Covid19Radar.ja.xlf Line 237

I confirmed the fix on build 203.

**Comment by takapi-Jr** [comment]
解消しました。

It has been resolved.
Build number : (Android)204
