### ISSUE TITLE
 アプリの利用規約画面に必要のないUIを排したい

### ISSUE THREAD

**Issue by sam-osamu** [Covid-19Radar/Covid19Radar#687]
**Is your feature request related to a problem? Please describe.**

アプリの利用規約として厚生労働省のホームページが表示されておりますが、
アプリの機能に関係ないホームボタンやメニュー等までもが一緒に表示されております。
想定としては画面最下部の[I accept the Terms of Use]ボタンが押下されることだと考えますが、
それ以外にも意図しない画面遷移の導線が存在し、ユーザが混乱してしまうかと思います。

**Describe the solution you'd like**

アプリの利用規約画面として使用しないUIを表示させない

**Describe alternatives you've considered**

厚生労働省ホームページから利用規約本文を引用した静的htmlを作成することは必要ですが、  
そこからさらに二通りの方法があると考えました。

1. 文字リソースとして埋め込む
1. サーバを設置し、そこにアップロードする

メンテナンスの利便性の点から私個人としては2を推したいのですが、一個人で対応できる事なのかが懸念です。  
ライセンスのページはAzure上で公開されているhtmlを参照しているようですので同様の対応が可能かと思いますが、  
管理者様の助力をいただかないと難しい事項（htmlファイルのアップロードやURLの発行等々）があると考えています。

**Comment by sam-osamu** [comment]
該当のページを表示したキャプチャーを添付します（Android版/エミュレータより取得）。
[Terms of use]の下部に表示されている青いホームボタンやメニュー、パンくずリストをについて言及したく起票しました。
（実際、私はホームボタンを押下してブラウザが起動したのに気づかず、そのまま厚生省のページをさまよいました…）

![Screenshot_1593230357](https://user-images.githubusercontent.com/46447427/85914204-44508200-b876-11ea-961d-9b849680afa9.png)

**Comment by Niccari** [comment]
1.0.0(6/19時点の製品版)のコードでは、以下ページが利用規約、プライバシーポリシーで使用されていました。
* 利用規約
https://covid19radarjpnprod.z11.web.core.windows.net/ja/termofuse.html

* プライバシーポリシー
https://covid19radarjpnprod.z11.web.core.windows.net/ja/privacypolicy.html

ただ、1.0.0→1.1.0への修正の途中で何らかの理由で厚生労働省上のページに置き換えがされています。

* 利用規約
https://www.mhlw.go.jp/stf/seisakunitsuite/japanese_rk_00028.html

* プライバシーポリシー
https://www.mhlw.go.jp/stf/seisakunitsuite/japanese_pp_00027.html

**Comment by sam-osamu** [comment]
> 
> 
> 1.0.0(6/19時点の製品版)のコードでは、以下ページが利用規約、プライバシーポリシーで使用されていました。
> 
>     * 利用規約
>       https://covid19radarjpnprod.z11.web.core.windows.net/ja/termofuse.html
> 
>     * プライバシーポリシー
>       https://covid19radarjpnprod.z11.web.core.windows.net/ja/privacypolicy.html
> 
> 
> ただ、1.0.0→1.1.0への修正の途中で何らかの理由で厚生労働省上のページに置き換えがされています。
> 
>     * 利用規約
>       https://www.mhlw.go.jp/stf/seisakunitsuite/japanese_rk_00028.html
> 
>     * プライバシーポリシー
>       https://www.mhlw.go.jp/stf/seisakunitsuite/japanese_pp_00027.html

ご返信・情報連携ありがとうございます。
既に存在していたのですね…存じておりませんでした。
そうなると、このIssueで対応できる事は無さそうですのでCloseとさせていただきます。

**Comment by shogo82148** [comment]
このコミットのようですね https://github.com/Covid-19Radar/Covid19Radar/commit/d831eb2446866b389ca6192b5296c0df6bcad123

@kazumihirose 個人的にも利用規約のUIは気になっていたので、変更の理由を共有していただけないでしょうか？
