### ISSUE TITLE
The link to the GitHub page of LP is the previous repository.

### ISSUE THREAD

**Issue by sogaoh** [Covid-19Radar/Covid19Radar#69]
LPのGitHubページヘのリンク先が以前のリポジトリになっている

https://lp-covid-19radarjapan.studio.design/
を少し下にスクロールしたときに表示されるGitHubページのリンク先が

https://github.com/kazumihirose/Covid19Radar/blob/master/README.md

になっている。

https://github.com/Covid-19Radar/Covid19Radar/blob/master/README.md

に更新すべきと思う。

[Screenshot]
![lp-link-old_20200425-1730](https://user-images.githubusercontent.com/2090887/80275739-310e2280-871e-11ea-9cfc-09471cfd4b26.png)

**Comment by changeworld** [comment]
@sogaoh 

ご指摘ありがとうございました。このリポジトリとは別で管理されているサイトのため、該当ファイルの管理者に共有させていただきます。

**Comment by noriji** [comment]
@sogaoh @changeworld 
ご指摘いただいた部分のURLを更新しております。

https://lp-covid-19radarjapan.studio.design
