### ISSUE TITLE
iOSとAndroidでDrawer（メニュー）が表示されるアニメーションが異なる

### ISSUE THREAD

**Issue by sear-azazel** [Covid-19Radar/Covid19Radar#693]
**Is your feature request related to a problem? Please describe.**
ホーム画面のハンバーガアイコンをタップするとDrawer（メニュー）が
- iOS: ホーム画面を右へプッシュする形で表示される
- Android: ホーム画面に被さる形で表示される

**Describe the solution you'd like**
- UIは統一した方が良い
- Google製アプリなどのDrawerは、ホーム画面に被さる形で表示されるため、この仕様が望ましいと思われる

**Describe alternatives you've considered**
- MasterDetailPageのMasterBehaviorプロパティを"Popover"にする
  - Xamarinでは、iOSには対応していない（iPadOSには対応している）
  - 参考URL: 
    - http://furuya02.hatenablog.com/entry/2015/04/22/012631
    - https://forums.xamarin.com/discussion/100963/master-detail-menu-slide-over-top-of-detail-page-on-ios
- [SlideOverKit](https://github.com/XAM-Consulting/SlideOverKit) を利用する
  - 単純な実装（改修）ではない

**Additional context**

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも検討したいと思いま
