### ISSUE TITLE
future/create how-to-use for iOS.

### ISSUE THREAD

**Issue by kmikage** [Covid-19Radar/Covid19Radar#7]
creating how-to-use.

**Comment by kmikage** [comment]
pull request #14 .
日本語版をとりあえず書きました。
英訳・英語版スクショは、どなたかお願いできれば幸いです。

**Comment by kazumihirose** [comment]
ちょっと、今後変わる可能性の高い画面もありますので、随時変更などお付き合いいただけますとありがたいです。
