### ISSUE TITLE
(優先度：高)(Critical?：Yes) 使用停止後もSecureStorageにSecret, ユーザー情報が残っている

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#700]
**Describe the bug**
SecureStorageにユーザー情報を保存していますが、使用停止の操作後も保持されています。また、iOSにおいてはKeyChainに情報が保存されるため、アプリをアンインストール後もユーザー情報が残っています。
このことから、[利用規約 第10条](https://www.mhlw.go.jp/stf/seisakunitsuite/japanese_rk_00028.html)の"本アプリをアプリ導入端末から削除した場合は、その端末に記録されていた情報は、全て削除され、復元はできません。"に抵触する恐れがあります。

**To Reproduce**
### 使用停止の場合
1. アプリを新規インストールする
2. チュートリアルを完了する
3. 利用停止処理を行う
4. App.xamlの`if (userDataService.IsExistUserData)`あたりにブレークポイントを設定
5. デバッグを開始する

### アプリアンインストール(iOS)
1. アプリを新規インストールする
2. チュートリアルを完了する
3. アプリをアンインストールする
4. App.xamlの`if (userDataService.IsExistUserData)`あたりにブレークポイントを設定
5. デバッグを開始＋アプリをインストールする

**Expected behavior**
上記操作後、アプリを再度起動したときにユーザー情報が存在していないこと

**Screenshots**
なし

**Smartphone (please complete the following information):**
### Android
 - Device: iPhone 11 Emulator
 - OS: iOS 13.5.1
 - Browser safari
 - Version 1.1.0 commit: b40647872de035ccfdcd3ba774b875d22bc7970d

### iOS
 - Device: Nexus 7 Emulator
 - OS: Android 10.0
 - Browser chrome
 - Version 1.1.0 commit: b40647872de035ccfdcd3ba774b875d22bc7970d

**Additional context**
iOSでアプリアンインストール後にSecretStorageを削除する方法として、[Xamarinのissue](https://github.com/xamarin/Essentials/issues/728)では再インストール後の初回起動時に削除する方法が提示されています(アプリのアンインストール時に削除はできないとも記載されています)。ただ、この方法でもデータ自体は残ります。

利用停止時のユーザー情報の削除は、UserDataService.ResetAllDataAsyncで
`SecureStorage.Remove(AppConstants.StorageKey.UserData);`
を実施することで削除されます。

**Comment by yamachu** [comment]
Androidの場合manifestのallowBackupの値でアンインストール時に削除を行うことが可能そうです。
iOSの場合は提示してくださった方法以外SecureStorageを使った場合の値破棄は難しそうですね…

**Comment by kazumihirose** [comment]
対応しました。
