### ISSUE TITLE
[ios]利用規約同意画面、プライバシーポリシー同意画面、各文書の末尾以降もスクロールできる。

### ISSUE THREAD

**Issue by du-pre** [Covid-19Radar/Covid19Radar#701]
**Describe the bug**
[ios]利用規約同意画面、プライバシーポリシー同意画面にて、
利用規約の末尾、プライバシーポリシーの末尾以降もスクロールできてしまいます。

**To Reproduce**
利用規約同意画面、プライバシーポリシー同意画面でスクロールする。

**Expected behavior**
利用規約文、プライバシーポリシーの末尾以降は、スクロールできない。

**Screenshots**
![IMG_9771](https://user-images.githubusercontent.com/67505578/85936754-74605980-b938-11ea-98c6-1f0e32453f3a.PNG)
![IMG_9773](https://user-images.githubusercontent.com/67505578/85936756-76c2b380-b938-11ea-828a-c533d9ca6cc5.PNG)

**Smartphone (please complete the following information):**
 - Device: [iphone8]
 - OS: [iOS13.5.1]
 - Version [1.0.0]

**Comment by Niccari** [comment]
ご確認ありがとうございます。本件、以下の内容と同件と見られます。
https://github.com/Covid-19Radar/Covid19Radar/issues/463

**Comment by du-pre** [comment]
確認不足で失礼いたしました。
クローズ致します。
