### ISSUE TITLE
ボタンを連打すると遷移先の画面が複数回表示される

### ISSUE THREAD

**Issue by f-miyu** [Covid-19Radar/Covid19Radar#707]
**Describe the bug**
[陽性者との接触を確認する]ボタンなどを連打すると、遷移先の画面が複数回表示される

**To Reproduce**
1. [陽性者との接触を確認する]ボタンを連打する
2. 遷移先の画面が複数回表示される

**Expected behavior**
遷移先の画面が１回のみ表示される

**Additional context**
連打して複数回遷移するのは、ほぼAndroidの方ですが、チュートリアルの[接触検知をご利用いただくために]の画面の[有効にする]ボタンを連打すると、iOSでも起きます

**Comment by akashima** [comment]
類似事例としてはこちらですね。

https://github.com/Covid-19Radar/Covid19Radar/issues/538
