### ISSUE TITLE
接触一覧ページの"件"がローカライズの対象になっていない

### ISSUE THREAD

**Issue by watanabetoshinori** [Covid-19Radar/Covid19Radar#713]
過去14日間の接触一覧ページ(ExposuresPage)の以下のテキストがローカライズの対象になっていないようです。

[ExposuresPage.xaml#L31](https://github.com/Covid-19Radar/Covid19Radar/blob/master/Covid19Radar/Covid19Radar/Views/HomePage/ExposuresPage.xaml#L31)
```
<Span Text="件" />
```

**Comment by kazumihirose** [comment]
Issue起票大変ありがとうございます。
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
