### ISSUE TITLE
プライバシーポリシーのスクロールが何もないのに続いているため消したい

### ISSUE THREAD

**Issue by Akihiro0710** [Covid-19Radar/Covid19Radar#718]
**Describe the bug**
プライバシーポリシーページのレイアウト修正

**To Reproduce**
1. Go to 'menu'
2. Click on 'privacy policy'
3. Scroll down and see error

**Expected behavior**
コンテンツのサイズでスクロールが終了する

**Smartphone (please complete the following information):**
 - Device: iPhone 8 Plus
 - OS: iOS13.5.1
 - Browser safari

**Comment by shinriyo** [comment]
Related Ticket #625

**Comment by kazumihirose** [comment]
#625 にて、マージ済みです。
また、Issue起票大変ありがとうございます。
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
