### ISSUE TITLE
設定画面においてのライセンスのユーザビリティ向上

### ISSUE THREAD

**Issue by yutotakano** [Covid-19Radar/Covid19Radar#720]
**Describe the bug**
アプリ設定画面において、License（ライセンス）と書かれた列だけ不自然に右寄りになっている。
左側が空白になっているため、上から順に見ていく人は「ん？ここにはテキストがあるはずなのだろうか？」と空白の場所を違和感をもって凝視すると思われる。
さらに、リンクなのかリンクじゃないのか、青いだけだと分かりづらい。リンクを押して離す前にもスタイルに全く変化がないため、押せる物なのかどうかも分かりづらい。ユーザビリティの点（分かりやすさ、自明さ）から、これは改善すべきだと考える。

**To Reproduce**
1. アプリを開く
2. 左のメニューより、設定画面に入る
3. （押したときのスタイルを見る場合、ライセンスを押しながら引っ張ってみる。ほかのスイッチなども押しながら引っ張ってみて比べる）

**Expected behavior**
左寄りにすべき。GestureRecognizerは列（フレーム）全体にかかっていることからも、不自然さを作り出す以外特に右寄りにする意味は無いと思う。もともとのデザインを[XDで見ても](https://xd.adobe.com/view/8a430621-fe72-45a7-4acf-43fa7d73c181-fc72/screen/97820e07-789f-4679-a983-ac5b23e8e1e6/-)、ライセンスは左寄りに、そしてリンクだと強調させるために三点リーダがついている。これを尊重するべきではないだろうか。

使用中止と二つのスイッチは、どちらも押して離す前の時明確に外見の変化がある。これがあってこそユーザは「押した」と感じられる。現在のライセンスの挙動だと、間違えて押してしまっても何処を押したか分からない、又はそもそも押せると思わなかったなどという事態が発生する。

**Screenshots**
| 画像 | 押したときの反応GIF |
| --- | --- |
| <img src="https://i.imgur.com/J2eYRx1.jpg" width="350px"/> | <img src="https://i.imgur.com/UTTz72T.gif" width="350px"/> |

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Lite
 - OS: EMUI10
 - Version: 1.0.0 & 1.1.1

**Additional context**
特になし。

**Comment by yutotakano** [comment]
過去コミットを見たところ、71d6c49c9dc18a44f2c268375ba648b684dc2bf8で @kazumihirose さんが左寄りから右寄りに変えているのですが、なにか理由があったんでしょうか。

**Comment by yutotakano** [comment]
1.1.1にアップデートいたしましたが、上の二つのスイッチが無くなったので、ひときわ目立って見えます。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。

**Comment by yutotakano** [comment]
承知いたしました。お返事ありがとうございます。
