### ISSUE TITLE
About the Status of the APP（アプリのステタスについて）

### ISSUE THREAD

**Issue by kishorepal** [Covid-19Radar/Covid19Radar#722]
**Application Status**
How can a general User understand the APP is working perfectly in Background (Specially Old age people) ?
一般的なユーザ（特に高齢者）にとって、裏でアプリが動いているか検出しているか、わかりにくいです。

**Describe the solution you'd like**
It is better to show the Status in Different Color Big Font Size Test with some Additional Information.
Also, If there are any Voice Dialog based Notification, will be very helpful.

太字と違う色と付けて、少し情報を追加してステタスを表示すれば、分かりやすくなると思います。それに加えて、Activityを認識して、徹底的に音声に通知すれば、役に立つと思います。

**Comment by kazumihirose** [comment]
Issue起票大変ありがとうございます。
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
