### ISSUE TITLE
(優先度：低)(Critical?：No) 陽性情報の入力(NotifyOtherPage)画面 登録ダイアログでキャンセルしたときのダイアログは不要

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#725]
**Describe the bug**
陽性情報の入力(NotifyOtherPage)画面で'登録する'をタップすると登録ダイアログが出る。ここでCancelを押すと'キャンセルしました'とダイアログが出るが、これによりユーザーの操作の手間が1ステップ増えている。画面が通常表示に戻ることでキャンセルしたことがわかるので、キャンセルダイアログを削除して良いのでは

**To Reproduce**
1. メニュー画面を開く
2. '陽性情報の登録'をタップ
3. '同意して陽性登録する'をタップ
4. 8桁の任意の処理番号を入力する
5. '登録する'をタップ
6. 'Cancel'をタップ

**Expected behavior**
登録ダイアログがdismissした後、キャンセルダイアログが表示されないこと

**Screenshots**
* 登録ダイアログ
![スクリーンショット 2020-07-04 9 28](https://user-images.githubusercontent.com/30116202/86502006-7d8a7400-bdd9-11ea-8dd0-04f9868d3706.jpeg)

* キャンセルダイアログ
![Simulator Screen Shot - iPhone 11 - 2020-07-04 at 08 44 59](https://user-images.githubusercontent.com/30116202/86502039-bd515b80-bdd9-11ea-91b1-ee41df9d1c0f.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 (Emulator)
 - OS: iOS 13.5
 - Browser safari
 - Version 1.1.1

**Additional context**
なし

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
