### ISSUE TITLE
Non localised picture of "New Lifestyle"

### ISSUE THREAD

**Issue by k0a8t1o6** [Covid-19Radar/Covid19Radar#731]
**Describe the bug**
Captions to each icon of "New Lifestyle" is in Japanese regardless of the application language.

**To Reproduce**
1. For iOS, Go to Setting of the phone
2. Scroll down to the app
3. Change "Preferred Language" to English, for instance"
4. Open the app
5. Select "Check close contacts"

Device language of Android may be changed instead of app's language.

**Expected behavior**
The image comes with English for English users.
English captions may be acceptable for other language speakers.

**Screenshots**
![IMG_7B9266D7ED74-1](https://user-images.githubusercontent.com/46238149/86910320-786c5280-c154-11ea-905d-191feeb405b6.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 13.5.1
 - Version 1.1.1

**Additional context**

**Comment by k0a8t1o6** [comment]
It looks like images with Japanese captions are used everywhere, such as in Help page.
Apparently the app fail to load English resources.
https://github.com/Covid-19Radar/Covid19Radar/tree/master/Covid19Radar/Covid19Radar.iOS/Resources/en.lproj

**Comment by nonoxp** [comment]
Works fine on Android (version 10).

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
