### ISSUE TITLE
Errors in the English Translation on the Consent Screen

### ISSUE THREAD

**Issue by yutotakano** [Covid-19Radar/Covid19Radar#732]
**Describe the bug**
The screen shown when pressing "Register Positive Test Result" is full of grammatical errors and ambiguous writing remenscent of machine translation.

**To Reproduce**
1. Launch the app
2. Tap on "Register positive test result"

**Expected behavior**
Proper English usage to ensure that foreigners in Japan are able to understand how the system works, and what implications there are for registering.

**Screenshots**
<img src="https://i.imgur.com/966S7jk.jpg" width="350px" />

**Smartphone (please complete the following information):**
 - Device: Huawei P30 Lite
 - OS: Android EMUI 10
 - Version 1.1.1

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
However, I would like to consider it on Covid19Radar as it is a very appreciated proposal.

**Comment by yutotakano** [comment]
Thank you for the response. I checked the official `cocoa-mhlw/cocoa` repository and apparently they had already fixed the issue. :)
