### ISSUE TITLE
Adaptive Icon に対応する

### ISSUE THREAD

**Issue by su8ru** [Covid-19Radar/Covid19Radar#736]
### Is your feature request related to a problem? Please describe.

ホーム画面にアプリアイコンを追加した際に、ホームアプリの設定通りの形にトリミングされず、正方形のアイコンになってしまいます。
また、Android O ではこの仕様を元にしたアニメーションが実装されており、特段の事情がない限りは対応しておくべきです。

When I add an app icon to the Home screen, it is not trimmed to the shape of the Home app's settings and becomes a square icon.
Also, Android O implements animations based on this specification, which should be supported by the app unless there are special circumstances.

### Describe the solution you'd like

[公式リファレンス](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) に書いてある仕様に沿って実装し、Adaptive Icon に対応させる。

Implement it according to the specification in [the official reference](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) to support Adaptive Icon.

### Additional context

**[screenshot] Covid19Radar / other apps**

![screenshot](https://user-images.githubusercontent.com/33474143/87039649-74aaff80-c22a-11ea-81bd-6ae2f5f9d18c.png)

私の環境が原因でしたら申し訳ありません。ご指摘いただければcloseします。

I'm sorry if it was my environment. I will close it if you point it out.

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
