### ISSUE TITLE
(優先度：低)(Critical?：No) iPhone SE(2016)でDynamic Typesを5/7にした時、TutorialPage1の本文とボタンが被ることがある

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#738]
**Describe the bug**
iPhone SE(2016)でDynamic Typesを5/7以上にした時、TutorialPage1のスクロールを一番下にすると本文とボタンが被る。

**To Reproduce**
1. 端末のDynamic Typesを5/7に設定
2. アプリをインストール
3. アプリを起動
4. 最初の画面(下図)にて、画面を一番下までスクロール

**Expected behavior**
本文を一番下までスクロールした時、"次へ"ボタンと重ならないこと

**Screenshots**
![IMG_0188](https://user-images.githubusercontent.com/30116202/87157518-5c55e600-c2f9-11ea-8809-97ccc1151f94.jpeg)

![IMG_0190](https://user-images.githubusercontent.com/30116202/87158894-68db3e00-c2fb-11ea-8b09-d0fc66c633a5.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhone SE(2016)
 - OS: iOS 14 Beta
 - Browser safari
 - Version 1.1.1

**Additional context**
None

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
