### ISSUE TITLE
(優先度：低)(Critical?：No) iPhone SE(2016)のメイン画面(英語版)で、使い方(How To Use)が厚生労働省のロゴと被ることがある

### ISSUE THREAD

**Issue by Niccari** [Covid-19Radar/Covid19Radar#739]
**Describe the bug**
iPhone SE(2016)のメイン画面(英語版)で、使い方(How To User)が厚生労働省のロゴと被ることがある。

**To Reproduce**
1. アプリもしくは端末の言語を英語に設定
2. メイン画面を開く

**Expected behavior**
厚生労働省のロゴ、使い方(How To Use)が被りなく表示されること

**Screenshots**
![IMG_0189](https://user-images.githubusercontent.com/30116202/87159162-dc7d4b00-c2fb-11ea-8e4e-87cdf9b34f24.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone SE(2016)
 - OS: iOS 14 Beta
 - Browser safari
 - Version 1.1.1

**Additional context**
None

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
