### ISSUE TITLE
（優先度：低）説明をもう少しわかりやすい表記に変える

### ISSUE THREAD

**Issue by YuikoIto** [Covid-19Radar/Covid19Radar#749]
**Is your feature request related to a problem? Please describe.**

東京都のこちらのサイトを見て思ったのですが、COCOAは少し日本語が難しすぎるのではという気がします。https://stopcovid19.metro.tokyo.lg.jp/flow

**Describe the solution you'd like**
ひらがなで書くとむしろ読みにくいので、噛み砕いた簡単な表記に変える
例えば、「このとき、接触した相手の接触符号の記録をアプリに行います。どちらかの利用者が陽性の登録を行うまでは接触の情報は利用されません。接触の履歴は14日後に消去されます。 ※接触符号は定期的に変わります」このような表現は人によっては難しく感じる気もする

**Describe alternatives you've considered**
噛み砕いた表現を嫌う方もいるとは思うので、あくまで専門用語を出来る限り使わない表現に変えるのみにする

**Additional context**
もし意図があってこの表記の場合はこちらのissueを閉じて下さい。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
