### ISSUE TITLE
Review and update translation in German

### ISSUE THREAD

**Issue by YuikoIto** [Covid-19Radar/Covid19Radar#752]
**Is your feature request related to a problem? Please describe.**
ドイツ語の翻訳部分の修正

Additional context

**Describe the solution you'd like**
多言語化をより充実させる

**Describe alternatives you've considered**
機械翻訳の部分が少し変なのでわかりやすく修正&正しい部分もneeds-review-translationのままなのでstatusのチェック。

**Additional context**

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも検討したいと思います。
