### ISSUE TITLE
If Bluetooth is OFF, The app shows an warning dialog only once

### ISSUE THREAD

**Issue by ykrtk** [Covid-19Radar/Covid19Radar#758]
**Describe the bug**
The app shows the warning dialog to indicate Bluetooth is OFF, ONLY ONCE, and keeps silent after 2nd time

**To Reproduce**
1. App is installed with Bluetooth being ON
2. Turn Bluetooth OFF on the phone
3. Launch the COCOA app
4. You can see the warning dialog saying Bluetooth is OFF, and asking you to turn it ON
5. Tap OK and switch to another app
6. Switch to COCOA again

**Expected behavior**
The COCOA app keeps warning Bluetooth is OFF, so that user doesn't forget about it

**Smartphone (please complete the following information):**
- Device: iPhoneX
- OS: iOS 13.6
- Version: App version 1.1.2

**Comment by kazumihirose** [comment]
This is not a COCOA code operated by the Ministry of Health, Labor and Welfare.
I am very sorry, but I would appreciate if the Ministry of Health, Labor and Welfare (COCOA) could issue/PR again.
Kindly thank you.
