### ISSUE TITLE
お問い合わせメールにAPPデバイス情報とアプリバージョンを記載

### ISSUE THREAD

**Issue by takish** [Covid-19Radar/Covid19Radar#760]
**Is your feature request related to a problem? Please describe.**
不具合対応を行う際に、どの機種でどのOSでどのバージョンで不具合が発生しているかを切り分けるためにiOSかAndroidかなどOSの情報とアプリのバージョンをデフォルトで付与できるようにしたい。

**Describe the solution you'd like**
InqueryPageViewModelのBodyの本文の前に差し込まれるようにしたい

**Describe alternatives you've considered**
GMSに対応していない機種などもあるので、そのあたりの方からのお問い合わせが発生したときにシステムの不具合なのか、現場の仕様上仕方がないことなのかに切り分ける必要がある。

**Additional context**

- 現状
<img width="200" alt="スクリーンショット 2020-07-20 22 45 31" src="https://user-images.githubusercontent.com/35608/88245883-be3c2580-ccd3-11ea-8f97-96f69451a752.jpg">

- 追加したいもの
以下の例のように本文との間に環境情報を追加する

<img width="200" alt="スクリーンショット 2020-07-20 22 45 31" src="https://user-images.githubusercontent.com/35608/88245877-baa89e80-ccd3-11ea-861a-18c58ffcfa24.jpg">

**Comment by Takym** [comment]
すみません。数字を打ち間違えてしまいました。修正済みです。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常にありがたいご提案でして、Covid19Radarでも検討したいと思います。
