### ISSUE TITLE
「非使用のAppを取り除く」が有効の場合、いつのまにかアプリが削除されてしまい機能しなくなる

### ISSUE THREAD

**Issue by maloninc** [Covid-19Radar/Covid19Radar#763]
**Describe the bug**
「非使用のAppを取り除く」が有効の場合、いつのまにかアプリが削除されてしまい機能しなくなる。

**To Reproduce**
1. 設定 > iTunes Store と App Store
2. 非使用のAppを取り除くを選択
3. おそらく1か月ほどアプリを起動しない状態を継続する
4. COCOAアプリが削除される。アプリアイコンは見えますが、アプリタイトルの左に雲のマークが付く

**Expected behavior**
非使用のAppを取り除くが選択されている場合に警告を表示する。

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: iOS 13.5.1

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
