### ISSUE TITLE
起動するとたまにチュートリアルからまた始まって、これまでの接触履歴がリセットされてしまう。

### ISSUE THREAD

**Issue by mnaruse** [Covid-19Radar/Covid19Radar#768]
**Describe the bug**

週1か隔週の頻度でアプリを起動しています。
すると、たまにチュートリアルからまた始まって、これまでの接触履歴がリセットされてしまう事象が発生します。
6月中旬にインストールしてから、これまでにおそらく2回発生しており、
1回目はチュートリアルから再開されたのは確実ですが、接触履歴がリセットされたかどうかはよく覚えていなくて自信ありません。
2回目は本日(8/1)に発生し、接触履歴のリセット(「8/1から0日間使用中」の表記)までされたことが確認できました。

**To Reproduce**

1. アプリを起動する。

**Expected behavior**

メイン画面が表示される。

**Smartphone (please complete the following information):**
 - Device: iPhone 7 Plus
 - OS: iOS13.5.1

**Additional context**

**Comment by emosei** [comment]
以下で記載と同様の事象がありました。

iPhone X
OS: iOS13.6

思い当たる操作は、AppleIDのサインアウトとサインインをしました。
なので、もしかしたら私の事象は仕様なのかもしれません。

**Comment by kazumihirose** [comment]
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
