### ISSUE TITLE
新型コロナに関する最新情報を表示する

### ISSUE THREAD

**Issue by Takym** [Covid-19Radar/Covid19Radar#770]
接触確認アプリから新型コロナに関する感染者数やワクチン・特効薬、統計情報等の最新情報を検索・閲覧・通知できる様にすれば便利ではないでしょうか。

**Comment by kazumihirose** [comment]
まず、Issueいただけました事ありがとうございます。
こちらは厚生労働省によって運用されているCOCOAのコードではありません。
大変恐縮なのですが、厚生労働省(COCOA)に再度Issue/PRなど頂ければ幸いです。
何卒宜しくお願い致します。
ただ、非常に有意義なご意見でして、コミュニティ版のソースコードへの反映は検討させていただきます。
