### ISSUE TITLE
project dead?

### ISSUE THREAD

**Issue by relevan** [Covid-19Radar/Covid19Radar#773]
現在 96 の issue と 32 の PR が放置されています。

1. OSS版のCovid19Radarプロジェクトは停止している状態ですか？
1. 新しいメンテナは求められていますか？
1. このプロジェクトに取り込まれた内容は、現在もCOCOAへ取り込まれる状況ですか？

**Comment by Takym** [comment]
厚生労働省公式のサポートにメールを送信してみました。現在返信待ちです。


2020年8月20日(木) 12:36 relevan <notifications@github.com>:

**Comment by peaceiris** [comment]
> https://twitter.com/masanork/status/1296836210015399936?s=20
>
> 当初の予定通り運用保守業者が引き継いでますよ

だそうです。

「開発は引き継がれているけど OSS としてはやらない」ってことですかね?

もし今後 OSS としてやるつもりがないのであれば Issue や Pull-request を作ってくれる人の時間を無駄にしないためにも、このリポジトリを Archive するなりして方針を示す必要があると思います。

**Comment by peaceiris** [comment]
[README](https://github.com/Covid-19Radar/Covid19Radar/blob/f2b75c7a2dc752513ad905a562768555be469922/README.ja.md) 冒頭には以下のような記述がありますが

> 「接触確認アプリは、厚労省の公式バージョンの一つのみ存在します。
> こちらのGitHubは、厚労省の公式アプリのコードそのものではなく、公式アプリの元になっているオープンソースコードです。こちらのコードはコミュニティによってメンテナンスされており、issueやプルリクが公式アプリに反映されるとは限りません。」

今後、引き継ぎ先が OSS として開発を続ける予定ではなく、フィードバックも公式アプリの方に反映されることがない (現状は取り込まれるでも、断られるでもなく放置の状態) のであれば Issue や Pull-request を作ってくれる人の時間を無駄にしないためにも、このリポジトリを Archive するなりして方針を示す必要があると思います。

**Comment by masakatsu-corp** [comment]
@runceel @darkcrash @kazumihirose @noriji 
オーガナイザーの方々は現在のプロジェクトのステータスについて何かご存知でしょうか？

**Comment by rocaz** [comment]
https://twitter.com/masanork/status/1296836210015399936?s=21

**Comment by runceel** [comment]
@masakatsu-corp 
コミットログの私の最終コミットの時期（そもそもコミット数もそんなに多くないですが…）を見て頂ければわかる通り、離れて久しいので現状は何も把握していません。

**Comment by darkcrash** [comment]
私もどうなるかは知りません。私個人は、既に手を離れているという認識ではあります。もちろん何か困ったことがあれば、力にはなれるように努力しますが。。。
個人的な想いで言えば、このリポジトリは有志の活動で、COCOAとは切り離された方が良いと思っています。COCOAは、気軽に修正できないですからね。現状は、ここに対してCOCOA向けにPRを出しても取り込まれる可能性はかなり低いと考えています。

重ねて、あくまで個人の意見でしかないことをご理解ください。

**Comment by noriji** [comment]
デザイン方面もですが、私もrunceelさんやdarkcrashさんと同じように、現状のCOCOAプロジェクトについての情報はわかりませんし、既に本コミュニティとCOCOAは切り離されているとも思っています。（今後、助言などを求められればお手伝いするつもりはありますが）
darkcrashさんも書かれていますが、COCOAの改善についてのPRをこちらにいただいてもCOCOA本体に取り込まれる可能性は限りなく低いという認識ではあります。

※あくまで個人の意見ですのでご承知おきください。

**Comment by masakatsu-corp** [comment]
返信ありがとうございます。

@darkcrash @noriji 
お二人ともこのリポジトリにPRを出してもCOCOAには取り込まれないとの認識のようですがそう思う理由はなんでしょうか？
@kazumihirose さんから何らかの周知等あったのでしょうか？

**Comment by noriji** [comment]
オーガナイザーとして私にもメール通知があったため、こちら返信させていただいております。

> お二人ともこのリポジトリにPRを出してもCOCOAには取り込まれないとの認識のようですがそう思う理由はなんでしょうか？

こちらの件に関しては、READ.MEに既に以下の文言を記載をしておりましたので、ご確認いただけますと幸いです。
「接触確認アプリは、厚労省の公式バージョンの一つのみ存在します。
こちらのGitHubは、厚労省の公式アプリのコードそのものではなく、公式アプリの元になっているオープンソースコードです。こちらのコードはコミュニティによってメンテナンスされており、issueやプルリクが公式アプリに反映されるとは限りません。」
https://github.com/Covid-19Radar/Covid19Radar/blob/master/README.ja.md

また、kazumihiroseさんから周知があった等はありません。

**Comment by masakatsu-corp** [comment]
@noriji 返信ありがとうございます。
READMEの文言は私も確認していたのですが、されるかされないかわからないという程度の認識でした。
取り込まれる可能性が限りなく低いというレベルだとは認識できていなかったです。

**Comment by darkcrash** [comment]
個人的というのは、私が思う取り込まれにくい要素があると思ってました。

いくつかのIssueにもありましたが、元々の仕様書があるためにこの変更は難しいところ。

PRの内容検証をする体制が少なくても私たちにはない点。

ソース開示の義務はあっても、PRを取り込む義務まではないところ。

など、それを必要とするかどうかを含めて、今そうなるだろうか、、、と思ってます。

アプリの対象者が広く、不具合が発生した時に修正者に火の粉が落ちるのもおかしいのですが、そうなりかねない部分もありますね。
なので、分離されて欲しいとは思います

**Comment by runceel** [comment]
因みに私視点ですが以下のような感じです。

- 3 月 4 月ごろから Covid-19 Radar で手伝えるところがあるので手伝いたいと言う気持ちで可能な範囲で手伝った
- なんか厚生労働省からリリースされることになったので頑張った（私の貢献度合いは、頑張ったと言えるほど頑張ってないですが…
- リリース後は 1 国 1 アプリなので厚労省の持ち物
- Covid-19 Radar として特にこちらに手伝ってほしいということも言われていないので手離れ
- 今回のこのスレッドは**個別アカウントに対してメンションが来た**ので個人で感じてることを返事しました
- 今後の展望は厚労省に聞かないと分からないし個々の開発者には国にパイプなんて普通ないので分からないし、いずれ発表されるだろうから急かす必要もないので窓口にも問い合わせてないので知らない

なので、総じて知らないという感じです

**Comment by masakatsu-corp** [comment]
@runceel 
> 個別アカウントに対してメンションが来た

不快に思われていたらすみません。
今回オーガナイザーとしてメンションした4名の皆様はCovid-19Radar Organizationのメンバーだったので何か知っているかと思いメンションした次第です。
https://github.com/orgs/Covid-19Radar/people

**Comment by runceel** [comment]
あ、すいません
何か知ってるからコメントしたのではなく個別に聞かれたので話しただけというのを強調したかっただけです
特に不快だとかそういうのではないです

**Comment by masakatsu-corp** [comment]
@Sakurann
Wikipedia に渉外担当としてお名前が記載されておりますが安田さんも他の方と同じご認識でしょうか？
https://ja.wikipedia.org/wiki/%E6%96%B0%E5%9E%8B%E3%82%B3%E3%83%AD%E3%83%8A%E3%82%A6%E3%82%A4%E3%83%AB%E3%82%B9%E6%8E%A5%E8%A7%A6%E7%A2%BA%E8%AA%8D%E3%82%A2%E3%83%97%E3%83%AA

**Comment by masakatsu-corp** [comment]
COCOAのリポジトリが公開されましたね。
https://github.com/cocoa-mhlw/cocoa

となるとやはりCovid19Radarとしては開発終了という事でしょうか。

**Comment by darkcrash** [comment]
ようやく別の道を行けるというところですかね。参考になるコードとして、他国に展開できる形にしたいとはコミュニティメンバーと話してましたので。

**Comment by masakatsu-corp** [comment]
@darkcrash 
なるほど。
という事はこれからは方針転換して日本依存コードを削除して世界で使える汎用的なアプリにしていき、
止まっていたプルリクのレビューやマージも進んでいくという認識で良いのでしょうか。

**Comment by darkcrash** [comment]
個人的にはそんな感じかなぁとは思ってます。これからメンバーと少しづつ整理してですね。

**Comment by relevan** [comment]
ありがとうございます。
プロジェクトの現状については概ね整理されてるかと思うので、このissueはクローズします。

issueで議論してくださった方々、また、COVID19Radarを作ってくださった有志の方々に大変感謝です。

**Comment by kazumihirose** [comment]
既に2日前にCloseされてしまったので、お答えするべきか悩んだのですが、お話しできる状態となりましたので、改めてご案内致します。

・OSS版のCovid19Radarプロジェクトは停止している状態ですか？

いえ、当初より目指したCovid19radarプロジェクトとして継続していきます。
誤解を招かないように、今後COCOAに関連する不要なリソースを元のCovid19radar状態へ戻していきます。純粋なサンプル実装としての整理を細々と進める予定です。

・新しいメンテナは求められていますか？
変わらずメンテナとして、運営運用は進めていきますが、一緒にメンテナになって頂けるのであれば、もちろん歓迎です。

・このプロジェクトに取り込まれた内容は、現在もCOCOAへ取り込まれる状況ですか？

いえ、READMEにも当初より記載があるとおり、このプロジェクトはCOCOAでは無く、当初よりCovid19radarです。

COCOAソースコードの元にはなりましたが、当然COCOAとは違い、公式のものでは無く、いわゆるCOCOAに対しての取り込みが行われるかは保証できません。元より別のプロジェクトです。

しかしながら、「COCOAとして」多くのPRやIssueをいただく事が多く、厚労省さんに整備した公式のCOCOAリポジトリをご案内出来ないか、様々なご意見や改善提案を正しい形で、フィードバック頂けるよう、公式でリポジトリを整備を進めていただけるようにお願いして協議を重ねて参りました。

先日、COCOA公式のリポジトリが整備され、時間こそかかってしまいましたが、ご案内できる状態となりました。
おそらくは、厚労省の中で様々な課題解決が必要であったと思われます。

今までのIssueとPRに対してご案内できない事、苦慮しておりました。お手間をかけてしまうのですが、何卒ご理解いただけましたら幸いです。
