### ISSUE TITLE
Should not use datetime to generate Notification id

### ISSUE THREAD

**Issue by csleead** [Covid-19Radar/Covid19Radar#87]
NotificationCreateApi is now using datetime to generate an ID, which is unsafe and may cause ID collision.
https://github.com/Covid-19Radar/Covid19Radar/blob/6acf85bf863681ce980f74309c2f338eaf5360d6/Covid19RadarAPI/NotificationCreateApi.cs#L58

**Comment by darkcrash** [comment]
Yes, this message is intended for simultaneous transmission, so we don't expect to send it many times at short intervals.

Instead, may need to update, delete, or retrieve the list.

**Comment by csleead** [comment]
> Yes, this message is intended for simultaneous transmission, so we don't expect to send it many times at short intervals.
> 
> Instead, may need to update, delete, or retrieve the list.

Sorry, I don't quite understand what you said.
What's the relation between id generation and your reply?
I actually don't have much knowledge about this api, could you please explain more?

**Comment by darkcrash** [comment]
> Sorry, I don't quite understand what you said.
> What's the relation between id generation and your reply?
> I actually don't have much knowledge about this api, could you please explain more?

I am not currently aware of a problem with id generation.
id access is the most efficient in CosmosDB.
It makes a lot of sense to keep it in a identifiable ID.
Consider if you have a good ID when considering future updates and deletions.

**Comment by csleead** [comment]
I guess we should just stick to GUID unless we have some strong reasons.

BTW, to my understanding, notifications should be only created and read in normal use cases, and deleted when house keeping, there is no need to update. Also, notifications are usually queried by creation time rather ID.

**Comment by darkcrash** [comment]
Let's see. The GUID might be good, too.
Internally, the treatment of "GUID" is infinitely better at zero.
However, i felt a little effort to have our API for the outside pass the GUID.

>BTW, to my understanding, notifications should be only created and read in normal use cases, and deleted when house keeping, there is no need to update. Also, notifications are usually queried by creation time rather ID.

This notification is sent all at once and is delivered to the client application without the provided uniform notification feature.
ref #56

**Comment by darkcrash** [comment]
step1. register broadcast notification our application from outside application using this api.
step2. polling user api by our client apps. user api is include newest notification timestamp.
step3. call Notification/Pull from our client app, got notification.
step4. local Notification in client device from client app.

not delete notification. because delete timing is nothing.

**Comment by darkcrash** [comment]
You can fix it if you want.

**Comment by csleead** [comment]
There it is.

Actually, I am not so sure whether this API should exist in the first place.
If the purpose of this API to create notification in case someone get infected etc, then the notification should be created in the update status API rather than such a **hackable** API.

**Comment by darkcrash** [comment]
Thank you.
Right. This is not an infection notification, but an attempt to send regular messages to current beta testers.

**Comment by csleead** [comment]
You should have told me it is a testing API earlier. :frowning:
Anyway, if it is just for testing, we better doing something, say a feature toggle, to avoid this from being released to production.

**Comment by darkcrash** [comment]
Sorry. There was not enough way to communicate.
This is experimental, but it is likely to be actually used. So it's not dedicated to our tests, it's about knowing the proper notifications in our tests.
Notification timing, message, and content.
So now the purpose is to be displayed.
However, it will grow little by little.
