### ISSUE TITLE
local time LASTTIME

### ISSUE THREAD

**Issue by yoichinak** [Covid-19Radar/Covid19Radar#92]
LASTTIME of the detected beacons are displayed in UTC.
I hope it to appear in my local time.

**Comment by kazumihirose** [comment]
Thank you for contribute !

**Comment by takapi-Jr** [comment]
The time is displayed in UTC.
Build number : (Android)207

![Screenshot_20200428-201835](https://user-images.githubusercontent.com/25080529/80481674-ded33880-898d-11ea-8268-967d2734011e.png)

**Comment by takapi-Jr** [comment]
DBからデータ取得時、DateTimeKindの情報が取得できていないようです。
DateTimeKind information cannot be acquired when acquiring data from DB.

[When querying DateTime Fields from the DB, can I control the DateTimeKind?](https://stackoverrun.com/ja/q/11886606)

![2020-04-28 205120](https://user-images.githubusercontent.com/25080529/80484121-278cf080-8992-11ea-9b93-1b732d06c7ce.png)
