### ISSUE TITLE
Font color is white in Status Settings' Text Field

### ISSUE THREAD

**Issue by tacck** [Covid-19Radar/Covid19Radar#93]
I can't see characters that I enter at "Please enter the code" area.

ステータス設定の "Please enter the code" に入力した文字が白色のため、視認できない状態です。

Environment:

App version : Version 1.0 (203)
Operating system : iOS 13.3.1
Phone model : iPhone X

App version : Version 1.0 (204)
Operating system : Android 6.0.1
Phone model : SH-M04

**Comment by kazumihirose** [comment]
ありがとうございます。
実はデバッグ用につけたPickerでして、後に固定ステータス表示にきりかえます。
